src/inertia.js
Ex.:
Inertia.visit(url).then(() => alert('Do something after the page is loaded.'))
=> Add return on visit method, making possible the usage of promise.

src/inertia.js
=> Added array length check to navigationType

src/inertia.js
This is another take on @bradlc's work in #25.
This approach uses two callbacks (`resolveComponent` and `updatePage`) from the adapters, instead of just one (`setPage`).
This PR also makes some improvements to the loading indicators.
Closes #25
=> Improve visit cancellation

index.d.ts
Just like inertiajs/inertia-react@361d1fa
=> Set default types to the extended types

packages/inertia/src/debounce.js
Hey @reinink, just saw you commit this one & figured I'd contribute the slightly simpler one that I had laying around 😅
=> Simplify debounce

packages/inertia-react/src/Link.js, packages/inertia-svelte/src/Link.svelte, packages/inertia-vue/src/link.js
Declare new `headers` prop on the `InertiaLink` component for all adapters.
=> Add headers prop to InertiaLink components

packages/inertia/index.d.ts
=> Fix wrong typescript definition for the delete method (no data)

packages/inertia-react/src/App.js
=> [React] Shorthand nested layouts

packages/inertia-react/index.d.ts, packages/inertia-react/src/Link.js
=> [React] InertiaLink local event props

packages/inertia-vue/src/link.js
```vue
<InertiaLink :href="`/posts/${post.id}`" method="delete" @start="() => confirm('Are you sure you delete this post?')">
Delete post
</InertiaLink>
```
=> Inertia-link: Local event support

packages/inertia-vue/index.d.ts
I'm sorry, my recent PR was incomplete :weary:
=> Add missing import and add type for PluginObject<T>

packages/inertia-react/src/App.js, packages/inertia-react/src/Link.js, packages/inertia-svelte/src/App.svelte, packages/inertia-vue/src/app.js, packages/inertia-vue/src/link.js, packages/inertia-vue3/src/app.js, packages/inertia-vue3/src/link.js, packages/inertia/src/events.js, packages/inertia/src/inertia.js
=> Add first class support for validation errors

packages/inertia/src/files.js, packages/inertia/src/formData.js, packages/inertia/src/inertia.js
Closes #364
See: https://github.com/inertiajs/inertia/discussions/270
=> Support automatic form data conversion

packages/inertia-vue/src/form.js, packages/inertia-vue3/src/form.js
This PR brings Jetstream's `recentlySuccessful` form helper prop to Inertia. 
- The prop itself automatically resets to `false` after 2 seconds, unless you re-submit the form, in which case it is immediately reset.
In case the form is successful and the user successfully re-submits it again immediately, there is a chance that the previous `setTimeout` resets the `recentlySuccessful` status too soon due to the pending `setTimeout` timer from the 1st request. The clearTimeout mechanism solves this issue, by cancelling any existing timeout before the request is submitted.
=> Form: Add form.recentlySuccessful

packages/inertia-svelte/src/App.svelte, packages/inertia-svelte/src/Render.svelte, packages/inertia-svelte/src/index.js
This updates the limited nesting from #522 and allows for infinite layouts. It probably fixes #285 too by adding the appropriate file extension.
=> Replace nested hack with render component

packages/inertia/index.d.ts
=> Add typescript definition for errorBag

packages/inertia-react/index.d.ts
Hi 👋!
While programming, I patched inertia/react with the typescript variant of useForm. However, the current implementation is not generic, which makes type suggestions from my IDE useless.
Here is my implementation of useForm, thanks to #526 😁!
=> Generic useForm

packages/inertia-vue/index.d.ts
Exposes the form helper method to TypeScript
=> Expose Form Method To TypeScript

packages/inertia-vue/index.d.ts, packages/inertia-vue3/index.d.ts
Update list:
* Update vue2 adapter type definition file (like vue3, see #614)
* Add `isDirty` option to InertiaFormProps (see #660)
* Code formatting
=> Update Vue adapter type definition file

packages/inertia/index.d.ts
* Use the `Record` utility type
* Remove space
* Add the missing visit options
=> Update core type definition file

packages/inertia/index.d.ts
This PR will use an event map for the events so events are easier to use.
=> feat: enhance types

packages/inertia-react/src/useForm.js
A fix for a #656 issue that happens when you redirect away from a form page after a successful form action.
=> React: Fix "Can't perform a React state update on an unmounted component" error

packages/inertia-vue3/src/head.js
This PR improves on the work started in #719, which wasn't a complete solution, since while the children of the fragments were being rendered, they were not getting the `inertia` attribute applied to them. This PR corrects that.
=> Fix rendering of fragments in Head component in Vue 3 adapter

packages/inertia-vue3/index.d.ts
type, interface is not required to declare
=> Fix type definition file

packages/inertia-react/index.d.ts, packages/inertia-react/package.json
=> Add typings for createInertiaApp

packages/inertia-react/package.json
=> Allow React 18 as a peer dependency

packages/vue3/index.d.ts
Hello @reinink 
please see this PR. I think this change has to be implemented.
=> Type correction

package-lock.json, packages/vue3/src/head.ts, playgrounds/vue3/package.json
Added support for JSON schema script strings that the internal engine changes introduced in Vue 3.3 broke.
Last one (hopefully).
=> Refinements to node detection

packages/core/src/router.ts
=> Use `Omit` instead of `Exclude` in router types

packages/vue3/src/useForm.ts
Fix for bug introduced in #2052
=> Fix for default object in useForm

packages/core/src/page.ts
When merging #2051 there was a merge conflict which was resolved incorrectly. This PR addresses the merge errors.
=> Fix bad merge from takeover scroll PR

package-lock.json, packages/core/src/history.ts
Make sure `window` is defined before setting manual scroll restoration. When using SSR, this would not be defined and throws an error.
Fixes #2187
=> Fix SSR with scroll restoration

packages/core/build.js, packages/react/build.js, packages/vue3/build.js
This PR updates the build script to the new context API
=> Fix esbuild

packages/core/src/url.ts, packages/react/test-app/Pages/Visits/Data/Object.jsx, packages/svelte/test-app/Pages/Visits/Data/Object.svelte, packages/vue3/test-app/Pages/Visits/Data/Object.vue, tests/manual-visits.spec.ts
This PR is based on https://github.com/inertiajs/inertia/pull/2320
I messed up my local branch somehow and can't push to that PR, so replacing it with this one.
=> Corrected URL search parameter merge logic to match behavior prior to v2.0.8

packages/core/src/progress-component.ts
=> Don't show progress bar on prefetch hover

packages/core/src/progress-component.ts, packages/react/test-app/Pages/Progress.jsx, packages/react/test-app/app.jsx, tests/app/server.js
=> Fix progress bar not showing on subsequent page clicks

packages/core/src/prefetched.ts, packages/core/src/router.ts, tests/prefetch.spec.ts
=> Send `Purpose: prefetch` header on prefetching

packages/react/src/Form.ts
Also allow `ReactNode` instead of just a callback
=> Improve `children` prop of `<Form>` Component

packages/core/src/types.ts, packages/react/src/Form.ts, packages/react/test-app/Pages/FormComponent/ResetAttributes/ResetOnError.tsx, packages/react/test-app/Pages/FormComponent/ResetAttributes/ResetOnErrorFields.tsx, packages/react/test-app/Pages/FormComponent/ResetAttributes/ResetOnSuccess.tsx, packages/react/test-app/Pages/FormComponent/ResetAttributes/ResetOnSuccessFields.tsx, packages/react/test-app/Pages/FormComponent/SetDefaultsOnSuccess.tsx, packages/svelte/src/components/Form.svelte, packages/svelte/test-app/Pages/FormComponent/ResetAttributes/ResetOnError.svelte, packages/svelte/test-app/Pages/FormComponent/ResetAttributes/ResetOnErrorFields.svelte, packages/svelte/test-app/Pages/FormComponent/ResetAttributes/ResetOnSuccess.svelte, packages/svelte/test-app/Pages/FormComponent/ResetAttributes/ResetOnSuccessFields.svelte, packages/svelte/test-app/Pages/FormComponent/SetDefaultsOnSuccess.svelte, packages/vue3/src/form.ts, packages/vue3/test-app/Pages/FormComponent/ResetAttributes/ResetOnError.vue, packages/vue3/test-app/Pages/FormComponent/ResetAttributes/ResetOnErrorFields.vue, packages/vue3/test-app/Pages/FormComponent/ResetAttributes/ResetOnSuccess.vue, packages/vue3/test-app/Pages/FormComponent/ResetAttributes/ResetOnSuccessFields.vue, packages/vue3/test-app/Pages/FormComponent/SetDefaultsOnSuccess.vue, tests/app/server.js, tests/form-component.spec.ts
Reset entire form on success/error:
```tsx
const App = () => (
<Form method="post" action="/" resetOnError>
</Form>
)
const App = () => (
<Form method="post" action="/" resetOnSuccess>
</Form>
)
```
Reset specific fields on success/error:
```tsx
const App = () => (
<Form method="post" action="/" resetOnError={['name']}>
</Form>
)
const App = () => (
<Form method="post" action="/" resetOnSuccess={['name']}>
</Form>
)
```
Set current values as new defaults on success:
```tsx
const App = () => (
<Form method="post" action="/" setDefaultsOnSuccess>
</Form>
)
```
=> Add `resetOnError`, `resetOnSuccess`, `setDefaultsOnSuccess` to Form component

packages/svelte/package.json
=> Remove Svelte 5-next version constraint

.github/workflows/coding-standards.yml, packages/react/src/createInertiaApp.ts
=> Fix Coding Standards workflow

packages/core/package.json, packages/core/src/encryption.ts, packages/react/package.json, packages/react/test-app/package.json, packages/svelte/package.json, packages/svelte/test-app/package.json, packages/vue3/package.json, packages/vue3/test-app/package.json, playgrounds/svelte4/package.json, playgrounds/svelte5/package.json, playgrounds/vue3/package.json, pnpm-lock.yaml
Updated TypeScript to `^5.9.2` across all workspaces.
=> TypeScript upgrade

.github/workflows/publish.yml
=> Fix PNPM build

packages/core/src/index.ts, packages/core/src/infiniteScroll/queryString.ts, packages/core/src/url.ts, packages/react/test-app/Pages/InfiniteScroll/UpdateQueryString.tsx, packages/svelte/test-app/Pages/InfiniteScroll/UpdateQueryString.svelte, packages/vue3/test-app/Pages/InfiniteScroll/UpdateQueryString.vue, tests/app/helpers.js, tests/infinite-scroll.spec.ts
=> Preserve relative URL when `<InfiniteScroll>` updates query string

packages/vue3/src/form.ts, packages/vue3/src/infiniteScroll.ts, packages/vue3/test-app/Pages/FormComponent/Errors.vue
=> Use `SlotsType` to type-hint Vue slots
