src/inertia.js

This removes the local page state within Inertia and uses a callback approach instead. The specific JavaScript adapters can use this callback to update their local state. For example:
```js
created() {
Inertia.init(this.component, this.props, (component, props) => {
return Promise.resolve(this.resolveComponent(component)).then(instance => {
this.page.instance = instance
this.page.props = props
})
})
},
```

Replace local page state with callback

---

src/inertia.js

Thank you for this awesome framework, finally no more SPA worries. 👍🏻
This PR is just a little convention change...
> It's worth noting that the pool of IDs used by setInterval() and setTimeout() are shared, which means you can technically use clearInterval() and clearTimeout() interchangeably. However, for clarity, you should avoid doing so.
Source: [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/clearInterval)

Use the interchangeably clearTimeout instead of clearInterval

---

src/inertia.js

The `url` variable isn't used and both  the [`inertia-vue` docs](https://github.com/inertiajs/inertia-vue/blame/master/readme.md#L150) and the [`inertia-react` docs ](https://github.com/inertiajs/inertia-react/blame/master/readme.md#L152)reference the `reload` method with only an `options` object.

Fix reload signature

---

src/inertia.js

👋 This PR adds a `return` at the end of a `visit` so that the promise resolves only once navigation is complete.
Consider the following example:
```js
this.$inertia.visit('/').then(() => {
console.log('Navigated!')
})
```
The `visit` promise resolves before the navigation is complete:
The `visit` promise resolves once the navigation is complete:

visit: return setPage

---

src/inertia.js

Hi again. This is a quick fix for an issue with the progress bar where it is hiding before navigation is complete.

Set the page before hiding the progress bar

---

src/inertia.js

Right now it's not possible to pass query parameters to `Inertia.visit`, as the `data` variable gets passed as `data` to axios - which is only for actual POST/PUT/etc. data.
This PR allows making use of the data object, in case of a GET request.

Allow passing query parameters for GET requests

---

src/inertia.js

This adds a new `preserveState` option to Inertia, which is intended to be used by the adapters to either force a component rerender, or allow them to maintain any existing local state. Currently the adapters _do preserve state_, but that's often not preferred, especially for `GET` requests. This change makes this more of a "first class" feature.
The preserve state default is based on the method type, as follows:
- `visit()`: `{ preserveState: false }`
- `replace()`: `{ preserveState: true }`
- `post()`: `{ preserveState: true }`
- `put()`: `{ preserveState: true }`
- `patch()`: `{ preserveState: true }`
- `delete()`: `{ preserveState: false }`
These defaults can be changed on a per visit basis:
```js
// Preserve on GET (defaults to false)
this.$inertia.visit('/url', { preserveState: true …
```

Add option to preserve (local) state

---

index.d.ts

Unfortunately the initial implementation of the types didn't work out too good in practice.
Refactors I had to do to get things working:
- Use `namespace`s
- Use `module`s
Other changes:
- Simplified a few abstractions
- Reworked `PagePropsBeforeTransform` and `PageProps`
They're far from perfect, but they're working now. Will revisit later. Apparently typing libraries is very fragile, so I don't really want to make any further changes until we have some sort of test environment up.

Refactor TypeScript types

---

src/inertia.js

Since the `initialPage` gets generated on the server side, it will never contain the current window hash. This currently results in some unwanted behavior.
When you open: `http://localhost/view#something` you will end up at `http://localhost/view` without the current hash.
This PR adds it to the initial page so that you can retain the hash.

Pass initial window hash to initialPage

---

src/inertia.js

This PR adds support for partial reloads (#60). **This is still a work-in-progress.**
Partial reloads allow you to make subsequent visits to the _same page_ and only request a subset of the props (data) from the server. You do this with a new `only` option on visits.
```js
Inertia.reload({ only: ['users'] });
```
This requires coordination server-side to return only the subset of data. To do this Inertia passes along a new `X-Inertia-Only` header which includes a comma separated list of data keys that will returned. For example:
```php
X-Inertia-Only: users
```
When the server returns a subset of the data from the server, Inertia automatically merges it with the full page object from the previous request that's already in memory.
You can see the Laravel implementation of this here: …

Add support for partial reloads

---

src/inertia.js

Right now when Inertia detects an asset version change, it does a hard visit (full page reload) to force update the assets. During this process it must maintain both server-side and client-side state.
Server-side "state" includes any flash messages or validation errors. The Inertia middleware solves this by [reflashing the values](https://github.com/inertiajs/inertia-laravel/blob/master/src/Middleware.php#L21) automatically.
Client-side state also needs to be preserved. This PR updates Inertia to do this. The challenge is, by default, on a hard page reload, Inertia will not restore state. This is to match default browser behaviour.
To get around this, Inertia creates a temporary `inertia.hardVisit` boolean in local storage. If that value exists on reload, it will restore remembered state …

Preserve state on hard visit

---

index.d.ts

After coming across [`@types/express-serve-static-core`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express-serve-static-core/index.d.ts), I finally found a way of not needing to declare a module (which is an ES5 way of doing things).
Right now we just export the same things like we do in [index.js](https://github.com/inertiajs/inertia/blob/master/src/index.js).
We also export `PagePropsBeforeTransform`, `PageProps` and `Page`, since they're used in the `inertia-react` adapter.
All other types aren't exported anymore and stay private.
`PagePropsBeforeTransform` and `PageProps` can still be overwritten globally via declaration merging/interface augmentation.
I think @sebastiandedeyne should check this out in his practice project to see if everything still works …

Modernize typings

---

src/inertia.js

Some browsers apply the "overall" scroll to document.documentElement (the <html> element) and others to document.body (the <body> element). For compatibility with both, you have to apply the scrolling to both.

setScroll add html to query selector

---

src/modal.js

When using inertia with no styling framework, the width of the modal is bigger extends past the right hand side of the screen. 99% of modern web apply `box-sizing: border-box;` to all elements and so this is not noticeable, but when no CSS reset styles are used, this display issue is present.

add box-sizing: border-box to modal

---

src/inertia.js

Closes https://github.com/inertiajs/inertia/issues/74
In our app we wan't to set `preserveState` to `false` on successful form submits, and `true` when there are validation errors. The amount of code we need for this is pretty insane, this completely solves the problem.
If this gets accepted, I'll PR the necessary documentation and typing changes.

Support lazy preserveState & preserveScroll evaluation

---

packages/inertia-react/src/App.js
packages/inertia-svelte/src/App.svelte
packages/inertia-vue/src/app.js

Minor simplification for https://github.com/inertiajs/inertia/pull/116

Replace Promise with async

---

packages/inertia-vue/src/app.js

Excuse the huge number of changes in this PR.
This PR lets you pass along slots from your layout. [It's what this tweet was referring to](https://twitter.com/reinink/status/1300484695323443201).
This would be useful when you need to pass along non-Inertia Vue stuff.
My use case is wanting to add Inertia to an app that's currently a standard Laravel app returning Blade views. We have an addon ecosystem where third party developers can be returning views into our admin panel. We wanted a way to convert as much as possible to Inertia, but allow non-Inertia responses to keep working as they did pre-Inertia.
There's a handful of things you need to change about how you wire up Inertia. We talked about trying to streamline this eventually, but we can leave that for a separate PR.
1. Rather than …

Pass Vue scoped slots

---

packages/inertia-vue/src/app.js

This PR introduces a simpler way to define multi-level (persistent) layouts by using the array syntax
```
layout: [Foo, Bar, Baz]
```
Behaviour is as expected:
- When switching between two different pages that have the same exact layout stack, the layouts are all persisted. 
- When switching between two pages that share a portion of the same layout stack, only the portion until the first discrepancy is persisted, and the remainder will be re-rendered.
| Situation | Outcome |
|:------|:------|
| `layout: []` | Only renders the Page  |
| `layout: [Foo]` | Same as `layout: Foo` |
| `layout: [Foo, Bar, Baz, Bar]` |  Layout 'Bar' is rendered twice, as two separate instances |
| `layout: [Foo, Bar, Bar, Baz]` | Layout 'Bar' is rendered twice in a row, as two separate instances |

[Vue] Feature: Shorthand nested layouts (array syntax)

---

packages/inertia/src/inertia.js

This PR allows the user to set additional (custom) request headers on a request-by-request basis.
It checks whether the 'headers' object is set on the request 'options', and if it is, combines it with Inertia's headers.
Do note that Inertia's headers take priority and cannot be overwritten.
Usage:
- `this.$inertia.visit({ headers: { 'Custom-Header': 'value' }})`
- `this.$inertia.post('/endpoint', { 'id': 1 }, { headers: { 'Custom-Header': 'value' } })`
- ... (etc.)

Feature: Ability to define custom headers on a per-request basis

---

packages/inertia-svelte/package.json
packages/inertia-svelte/src/Link.svelte
packages/inertia-svelte/src/index.js
packages/inertia-svelte/src/link.js

The `use:inertia` directive can be used instead of the `InertiaLink` component to add Inertia behavior to any element in the DOM.
```svelte
<script>
import { inertia } from '@inertiajs/inertia-svelte'
</script>
<a href="/users" use:inertia>Users</a>
<button
use:inertia={{ href: '/users/100', method: 'post', data: { '_method': 'delete' }}}
class="btn-indigo"
on:click={() => alert('User deleted')}>
Delete
</button>
<a
href="/users/100"
use:inertia={{ method: 'post', data: { '_method': 'put', 'visited': true }}}>
Visited
</a>
```

[Svelte] Add use:inertia directive

---

packages/inertia-svelte/src/App.svelte
packages/inertia-svelte/src/Render.svelte

In order to support the same flexibility as the other adapter, I had to create a basic `h` function that can be used in two ways:
```js
/* 1 */ h(Layout, { title: 'Homepage' }, [page])
/* 2 */ h(Layout, [page])
```
Merging this PR is a breaking change. It requires that the `resolveComponent` closure passed to `InertiaApp` returns the page module and not just the default export.
```diff
import { InertiaApp } from '@inertiajs/inertia-svelte'
const app = document.getElementById('app')
new InertiaApp({
target: app,
props: {
initialPage: JSON.parse(app.dataset.page),
resolveComponent: name =>
-      import(`@/Pages/${name}.svelte`).then(module => module.default),
+      import(`@/Pages/${name}.svelte`),
},
})
```
Page components can then declare the desired layout inside the `<script …

[Svelte] Add support for persistent layout

---

packages/inertia/src/inertia.js

Re-implements #135 / #74 (removed [here](https://github.com/inertiajs/inertia/commit/6da241af975fae4f34f72986ca2eca765b18a4af#diff-e25ae5c7cf909bf9488eea033663bce8L120-L121)) to solve #229

Restore lazy evaluation of preserveScroll and preserveState

---

packages/inertia/src/inertia.js

Right now visits can only be cancelled from the global `start` event. However, there are use-cases for wanting to do this on a per-visit basis, which this PR adds support for. 👍 
Example:
```js
this.$inertia.post(`/users/${user.id}`, {
onStart: () => confirm('Are you sure you want to delete this user?'),
})
```

Add the ability to cancel a visit from the onStart() callback

---

packages/inertia/src/inertia.js

We currently have methods for `post()`, `put()`, `patch()` and `delete()`, but we don't have one for `get()`. Right now to do a GET visit you simply use `Inertia.visit()`. However, since people might expect a `get()` method to exist, this PR adds it. 👍 
```js
Inertia.get(url, data, options)
```

Add get() method

---

packages/inertia/index.d.ts

This PR updates the "manual visits" (https://inertiajs.com/manual-visits) options and method type definitions to match what's currently deployed.

Updates visit options types and adds get() method type definition

---

packages/inertia-svelte/src/link.js

Add update method to the use directive. This ensures options are updated when the directive parameters are dynamic.

[Svelte] Add auto update method to use:inertia

---

packages/inertia-vue/src/remember.js

I follow the documentation [Multiple components](https://inertiajs.com/local-state-caching#multiple-components) to set the remember key:
```js
remember: {
data: ['form'],
key: () => `Post/Edit:${this.post.id}`,
},
```
But it return an error:
I found is the `this` binding problem, this PR fixes it.
After using this PR to fix, arrow function cannot be used, can work with the following usage:
```js
remember: {
data: ['form'],
key() {
return `Post/Edit:${this.post.id}`
},
},
```

[inertia-vue] Fix remember key of this binding

---

packages/inertia-react/index.d.ts

The event props on the `InertiaLink` component should be optional, as suggested by their default values here: https://github.com/inertiajs/inertia/blob/052009a78aafdadcc4f060cca74475995ab2c6cd/packages/inertia-react/src/Link.js#L17-L22
Right now, I'm getting a bunch of type errors on `InertiaLink` components, because I'm not assigning a value to all of these methods:
```
Type '{ children: string; href: string; className: string; }' is missing the following properties from type 'InertiaLinkProps': onCancelToken, onStart, onProgress, onFinish, and 2 more.ts(2740)
```

[React] Update InertiaLink typings

---

packages/inertia-react/src/index.js
packages/inertia-svelte/src/index.js
packages/inertia-vue/src/index.js
packages/inertia-vue3/src/index.js

Fixes #255 
This PR adds titlecased named exports for the "app" and "link" components. This seems to be the standard with React, Vue.js and Svelte, and in fact is actually required with React (see #255).
Note, the old lowercase exports will still exists for backwards compatibility, but I'll update all the docs to use the new format, to encourage this "proper use". The lowercase versions will now be considered deprecated.

Use titlecase for named component exports

---

packages/inertia-react/.eslintrc.js
packages/inertia-react/package.json
packages/inertia-svelte/.eslintrc.js
packages/inertia-svelte/package.json
packages/inertia-vue/.eslintrc.js
packages/inertia-vue/package.json
packages/inertia-vue3/.eslintrc.js
packages/inertia-vue3/package.json
packages/inertia/.eslintrc.js
packages/inertia/package.json
packages/inertia/src/inertia.js

This PR adds support for URL hashes in Inertia.js (which are currently very much broken).
Currently it's not possible to make an Inertia visit that includes a hash in the URL. For example:
```html
<inertia-link url="/users#create">Create user</inertia-link>
```
This is because hashes are never sent from the browser to the server, which means when an Inertia response is received (which includes the `url` as part of the `page` object) and Inertia updates the history state with the new URL, the hash is gone.
We've been able to fix this by keeping track of the hash client-side, and appending it back on the URL when the Inertia response is received. Here's how:
1. When a request is made, we parse out the hash from the URL before making the request to the server.
2. When the response is …

Preserve url hash on navigation

---

packages/inertia/src/inertia.js

Fixes #260
This PR updates the promise proxy used to show the deprecation warning for `then`, `catch` and `finally` calls. It also now only tries to bind the `target` if the property is a function.

Fix promise deprecation warning

---

packages/inertia-react/index.d.ts
packages/inertia-react/src/Link.js
packages/inertia-svelte/src/Link.svelte
packages/inertia-vue/index.d.ts
packages/inertia-vue/src/link.js
packages/inertia-vue3/src/link.js
packages/inertia/index.d.ts

Fixes #164
This PR changes the default `preserveState` value in the link components from `false` to `false` for `get` visits, and `false` for `post|put|patch|delete` visits.

Set link preserveState default based on method

---

packages/inertia-react/src/Link.js
packages/inertia-svelte/src/Link.svelte
packages/inertia-svelte/src/link.js
packages/inertia-vue/src/link.js
packages/inertia-vue3/src/link.js
packages/inertia/src/inertia.js
packages/inertia/src/shouldIntercept.js

Closes #268
This PR adds a new "as" attribute to the Inertia link component that allows you to render a link as a different element. For example:
```vue
<inertia-link href="/example" as="div">Example</inertia-link>
<div>Example</div>
```
- ~~Update the Svelte adapter~~
The only adapter I'm not sure about is the Svelte adapter, since Svelte does not support dynamic elements yet (see [here](https://github.com/sveltejs/svelte/issues/2324)). It would literally mean a huge if statement for all the possible elements:
```js
{#if as === 'a'}
<a {...$$restProps} {href} on:click={visit}><slot /></a>
{:else if as ==='button'}
<button {...$$restProps} on:click={visit}><slot /></button>
{:else if as ==='div'}
<div {...$$restProps} on:click={visit}><slot /></div>
{/if}
```
Considering there is already …

Add link "as" option

---

packages/inertia-react/index.d.ts
packages/inertia-vue/index.d.ts

This PR adds InertiaLink's missing type definitions for React and Vue.
For React I also allowed all HTML attributes, since you can now do the following to create a button: `<InertiaLink as="button" type="button" href="/test">Some test!</InertiaLink>`. I'm not sure if this is the correct way to do this in React/TS, but I've tested this and it works and the builds finish without errors.
The Vue TS definitions probably also require a change to allow HTML attributes, but I couldn't figure out how to do this with Vue.
To test this I simply created a React TS app (`npx create-react-app my-app --template typescript`), installed inertia/inertia-react, made the changes within the node_modules folder and simply added an InertiaLink with new Inertia attributes and some default HTML attributes.

Update type definitions

---

packages/inertia/src/url.js

When using `window.location` or similar objects inside a `this.$method.post` (or similar request method), the request itself fails instantly due to calling `startsWith` on an object that does not have that method defined. 
As a result, the logic that does this check throws an error, which is caught instantly inside the same method, and instead returns a differently-formatted fallback URL that (in this case) causes the request URL to become malformed.
By calling `toString` on the object first, we essentially solve this problem, as the string object does have the `startsWith` method defined. Calling `toString` on a string is fine as well, and simply returns the existing string.
**Example**:
URL: `http://example.test/templates/1/variants/1`
Request: `this.$inertia.post(window.location)` …

Fix: hrefToUrl can call startsWith on Objects

---

packages/inertia-vue/index.d.ts

Following the recent changes on client-side framework setup:
```js
import { App, plugin } from '@inertiajs/inertia-vue'
```

Add Typescript definitions for 'App' and 'plugin' named imports

---

packages/inertia/src/inertia.js

The goal with `Inertia.reload()` is to refresh the page data (props) using a nice terse API. This method is similar to `location.reload()`, except `location.reload()` also preserves the scroll position, where `Inertia.reload()` doesn't currently. This PR updates it to do that.
This also forces the `preserveState` to `true`, instead of allowing you to override this via the `options`. If you don't want `preserveScroll` and `preserveState`, use a different method. 👍 
I also took the opportunity to break the dependency on `Inertia.replace()`, which is being deprecated.
We also don't need to explicitly set `replace: true`, since that happens automatically by making a visit to the same URL.

Update reload() method to preserve scroll position

---

packages/inertia/src/inertia.js

Closes #292
This PR adds a deprecation notice for the `Inertia.replace()` method, which has a number of issues (see #292).

Add deprecation notice for replace() method

---

packages/inertia/src/events.js
packages/inertia/src/inertia.js

Fixes #305
This PR fixes a regression that happened with the recent "finish" event changes. While the "start" and "finish" events are firing in the right sequence, the "finish" event (and callback) is now firing twice. This is because we're not checking to see if the last visit has completed before cancelling it.

Prevent finish event from firing twice

---

packages/inertia/src/inertia.js

Fixes #278
Fixes #295 
This fixes an issue where, when transforming props, if you put non-primitives (functions/classes) into your page props, it generates the following error:
```
Uncaught (in promise) DOMException: Failed to execute 'replaceState' on 'History': function () { ... } could not be cloned.
```
This is because the object that's put in history state must be something that can be serialized, and non-primitives cannot be.
To fix this, we need to deep clone the `page` object, and then do the props transforming on that, and then pass that to the `swapComponent()` method to be used in our apps.

Clone page before transforming props

---

packages/inertia-react/package.json
packages/inertia-svelte/package.json
packages/inertia-vue/package.json
packages/inertia-vue3/package.json
packages/inertia/package.json

This allows npm to display links like this:
This is useful because on Google, results for some queries including `inertia` still show the npm page higher than the GitHub repo and homepage.

Add links to be read out by npm

---

packages/inertia-react/index.d.ts
packages/inertia/index.d.ts

- Set the return type for `usePage` to `Inertia.Page` instead of `Inertia.PageProps`
- Add `scrollRegions` and `rememberedState` to `Page`
Resolves #321 
/cc @sebastiandedeyne

Fix type definition for usePage and add missing properties to Page

---

packages/inertia/index.d.ts

Fix for [issue: before event not included in InertiaEvent definition](https://github.com/inertiajs/inertia/issues/324)

Added missing 'before' event to InertiaEvent

---

packages/inertia/index.d.ts

According to these lines
https://github.com/inertiajs/inertia/blob/173b35933d883c5e1ef4beda482e200ad49b88c4/packages/inertia/src/inertia.js#L285-L286
and a quick check on my end using `preserveState: (pageProps) => console.log(pageProps);` which gives me the Page object and not the PageProps object:
The typings of `preserveScroll` and `preserveState` should be `Page<Inertia.PageProps>` instead of `Inertia.PageProps`.
This seems to be related to/have been "caused by" https://github.com/inertiajs/inertia/issues/321 and https://github.com/inertiajs/inertia/pull/323 (that PR is also correct and doesn't need to be reverted, as far as I can tell).

Fix typings for preserveScroll and preserveState

---

packages/inertia/src/url.js

This PR updates Inertia core to automatically encode query string values. This is important for situations where a query string value might include an unsafe character, such as an `&`. By using `encodeValuesOnly: true` instead of `encode: true`, the array format remains nicer looking.
I've also updated the array format to omit indices. So instead of `key[0]=value`, it's now `key[]=value`.
Consider a search for "jonathan & amy" with an array of statuses, the final query string will be:
```
/families?search=jonathan%20%26%20amy&statuses[]=member&statuses[]=guest
```
Instead of:
```
/families?search=jonathan%20&%20amy&statuses[0]=member&statuses[1]=guest
```
Eventually I'd like to actually expose some options for Inertia to give developers the choice on what array format to use (see #282).

Improve query string formatting

---

packages/inertia-react/src/PageContext.js

Presently in the react devtools we have this:
Context.Provider there being the pageContext we create as that is the default name,
but it's possible to name the contexts which makes navigating the react tree much nicer - After this pull request it will display as:

Add a displayName to the PageContext

---

packages/inertia/src/inertia.js

While not technically part of the HTTP spec, browsers do support body data for `DELETE` requests. This PR adds the option to include data when making an `Inertia.delete()` request. Example use case:
```js
Inertia.delete('/other-sessions', {
password: this.form.pasword, // password required to delete other sessions
})
```
This fixes hacky workaround, such as [this one](https://github.com/laravel/jetstream/blob/c856ef6c3012a34e41b66e1cf3a7a48ac0b80c26/stubs/inertia/resources/js/Pages/Profile/LogoutOtherBrowserSessionsForm.vue#L116) in Jetstream.
This is a breaking change, as it changes the `Inertia.delete` method signature:
```js
// Before
Inertia.delete(url, options)
// After
Inertia.delete(url, data, options)
```

Add support for delete body data

---

packages/inertia/src/inertia.js

This PR adds first-class support for error bags via a new `X-Inertia-Error-Bag` header. This header instructs the server-side adapters to scope the errors within the error bag key provided. Meaning, the server-side adapters will have to be updated to support this feature.
```js
this.$inertia.post(`/users/${user.id}`, this.form, {
errorBag: 'editUser',
})
```
Now, any validation errors returned from the server for this request will be scoped to `$page.props.errors.editUser`.
Note, however, that the `onError` callback and `error` event will NOT be scoped. They will simply contain the errors from the error bag.

Add error bag support

---

packages/inertia-vue/src/app.js
packages/inertia-vue/src/form.js
packages/inertia-vue/src/remember.js

This PR brings a first-class form helper to InertiaJS, as part of the Inertia Plugin (`this.$inertia.form`). The goal here is to integrate Jetstream's form helper and to keep the signature as similar as possible to make migration easy, while also improving the developer experience at the same time.
As an example, let's imagine we're building an Inertia page where you can edit the user's details using an Inertia form. 
If you've used Inertia with Laravel Jetstream before, this will probably look very familiar:
```html
<template>
...
<input v-model="form.email" type="text" placeholder="foo@example.com" />
<input v-model="form.password" type="password" placeholder="Password" />
...
</template>
<script>
props: {
email: String, // The user's existing email, passed as an Inertia prop
},
data: …
```

Add Inertia Form to Vue 2 adapter

---

packages/inertia-vue3/src/app.js
packages/inertia-vue3/src/form.js
packages/inertia-vue3/src/index.js

This PR adds the same form helper that's available in the Vue 2 adapter to the Vue 3 adapter. It is literally identical. However, since we don't want this logic in core, we'll leave it duplicated for now.
Here's how to use it:
```vue
<template>
<form @submit.prevent="form.post('/login')">
<input type="text" v-model="form.email" :error="form.errors.email" />
<input type="password" v-model="form.password" :error="form.errors.password"/>
<button type="submit" :disabled="form.processing">Login</button>
</form>
</template>
<script>
export default {
data() {
return {
form: this.$inertia.form({
email: null,
password: null,
}),
}
},
}
</script>
```
It also comes with a `form.reset()` helper for resetting the form back to its original state. Or, if you want to only reset specific fields, you can …

Add Vue 3 form helper

---

packages/inertia-vue/src/form.js
packages/inertia-vue3/src/form.js

This PR adds a new `transform()` function to form helper, which allows you to modify the data prior to it being sent to the server.
```js
export default {
data() {
return {
form: this.$inertia.form({
email: null,
password: null,
remember: false,
}),
}
},
methods: {
submit() {
this.form
.transform(data => ({
...data,
remember: data.remember ? 'on' : '',
}))
.post('/login')
},
},
}
```

Form helper improvements

---

packages/inertia-vue/src/form.js
packages/inertia-vue3/src/form.js

This PR solves an issue with the form helper where errors are being cleared when you call `reset`, which causes issues. 
For example, imagine a situation where you have to confirm your password to continue (e.g. github's confirmation screen), and you enter your password incorrectly. What you'd want to happen here, is that the field gets cleared, and the error message is shown, however in the current implementation it looks as-if no error occurred and the field just got reset.

Fix: Prevent errors from being cleared on form reset

---

packages/inertia-vue/src/form.js
packages/inertia-vue3/src/form.js

This PR adds a new `form.wasSuccessful` property to form helper, to track if the form was successfully submitted. This is different than `form.recentlySuccessful`, in that it doesn't get reset after 2 seconds.

Add "wasSuccessful" property to form helper

---

packages/inertia-react/index.d.ts
packages/inertia-react/src/index.js
packages/inertia-react/src/useRemember.js

Closes #387
This PR renames the React `useRememberedState` hook to `useRemember`. The primary motivation here is to keep the adapters in sync as much as possible, as both the Vue adapters, as well as the Svelte adapter just use the word "remember" here. I also plan to add a `useRemember` hook to the Vue 3 adapter.
Note, this is not a breaking change, as `useRememberedState` still exists. However, if you use it, you'll get this deprecation warning:
> The "useRememberedState" hook has been deprecated and will be removed in a future release. Use "useRemember" instead.

Rename React "useRememberedState" hook to "useRemember"

---

packages/inertia-vue3/src/form.js
packages/inertia-vue3/src/remember.js

This PR updates the Vue 3 adapter to implement the remember `serialize` and `unserialize` functionality, necessary for the remember behaviour to work with the form helper.
It also fixes an issue with the form helper `serialize` method, where the errors were not being serialized properly.
Also, previously we used `JSON.parse(JSON.stringify(value))` to convert a reactive property to a plain value. It now uses the `toRaw` helper in Vue 3 to do this.

Fix remember serialization in Vue 3 adapter

---

packages/inertia-vue3/src/form.js
packages/inertia-vue3/src/index.js
packages/inertia-vue3/src/remember.js

Closes #388
This PR adds a new `useRemember` hook to the Vue 3 adapter.

Add "useRemember" hook to Vue 3 adapter

---

packages/inertia/src/inertia.js

This PR fixes an edge case where the remember history state is lost when making a visit to the same page component and while preserving state.
For example, if you're submitting a form, and you end up back on the same page (ie. to show errors), we want to make sure that all the remember data is preserved. Previously, since a visit happened, it was lost.

Use remember history state when visiting the same component and preserving state

---

packages/inertia-vue3/src/app.js
packages/inertia-vue3/src/form.js
packages/inertia-vue3/src/index.js

This is simply a maintenance change. I think it makes more sense to put the `useForm` hook in `form.js`, along with the form helper, instead of putting this in `app.js`.

Move "useForm" hook to form file in Vue 3 adapter

---

packages/inertia/src/inertia.js

Resolves #405
This PR adds a new `forceFormData` option to Inertia that forces Inertia to always convert the data to a `FormData` object, regardless of if there are files present.
```js
Inertia.post('/users', data, {
forceFormData: true,
})
```
This is useful for situations where your server-side framework needs to know what type of request is being sent.

Add visit option to force FormData encoding

---

packages/inertia-vue/src/form.js
packages/inertia-vue3/src/form.js

Currently you cannot submit a form via `GET` using the form helper, even though this is a totally valid thing to do. This adds support for that.
```js
this.form.get('/users')
```

Add GET support to form helper

---

packages/inertia/package.json

Apparently there is a [vulnerability](https://github.com/advisories/GHSA-4w2v-q235-vp99) in axios `0.21.0`. This PR updates the minimum version to the patch version, `0.21.1`.

Update axios versions due to vulnerability

---

packages/inertia-react/index.d.ts

If you want to change the default behavior of the `InertiaLink` component and you are going to use the `InertiaLinkProps` interface, properties will not be compatible.
```typescript
import {
InertiaLink as OriginalInertiaLink,
InertiaLinkProps,
} from '@inertiajs/inertia-react';
export const InertiaLink: React.FC<InertiaLinkProps> = (props) => {
const newProps = React.useMemo(() => {
// Update the default behavior...
}, [props]);
// This will throw an error:
//
// Type '(event: KeyboardEvent<HTMLAnchorElement> | MouseEvent<HTMLAnchorElement, MouseEvent>) => void'
//   is not assignable to type '(event: MouseEvent<HTMLElement, MouseEvent>) => void'
return <OriginalInertiaLink {...newProps} />;
}
```
That's why I updated the InertiaLinkProps, that way interfaces will be compatible.

Update the React definitions

---

packages/inertia/src/files.js
packages/inertia/src/formData.js

Fixes #512
This PR adds `Blob` support to Inertia, when determining if a request should be sent using `FormData`.

Add blob support

---

packages/inertia-react/src/index.js
packages/inertia-react/src/useForm.js

This PR adds the form helper to the React adapter, similar to the existing form helpers in the Vue 2 and Vue 3 adapters. The main difference between this form helper and the Vue form helper is that this one automatically remembers the form data and errors in history state. I actually think it makes sense to update the Vue form helpers to do the same thing.
```jsx
import React from 'react'
import { useForm } from '@inertiajs/inertia-react'
import TextInput from './TextInput'
import LoadingButton from './LoadingButton'
const { data, setData, post, processing, errors } = useForm({
name: '',
email: '',
})
function submit(event) {
event.preventDefault()
post('/users')
}
return (
<form onSubmit={submit}>
<TextInput label="Name" value={data.name} errors={errors.name} onChange={e => …
```

Add form helper to React adapter

---

packages/inertia-react/index.d.ts

Closes #523 
This [PR](#526) adds Typescript declarations for the `useForm` hook, used by the React adapter.

Add react form helper typings

---

packages/inertia-react/src/Link.js
packages/inertia-svelte/src/Link.svelte
packages/inertia-svelte/src/link.js
packages/inertia-vue/src/link.js
packages/inertia-vue3/src/link.js
packages/inertia/src/inertia.js
packages/inertia/src/url.js

This PR simplifies the `mergeDataIntoQueryString()` method implementation in Inertia core and all the adapters.
Previously this method normalized links to always make them use absolute URLs. Meaning if you had an `href` of `/about`, the `mergeDataIntoQueryString()` method would turn it into `http://yourdomain.com/about`. While this practically isn't a super big issue, it's an odd thing for a method that's simply responsible for merging data into the query strings. With this update, Inertia will no longer change link URLs. It will simply use whatever you provide. 👍 
That said, the primary motivation for this change is to remove the dependency on the `hrefToUrl()` method, which requires `window` access, and doesn't work in SSR mode (Node).

Simplify mergeDataIntoQueryString method

---

packages/inertia-react/src/useForm.js

Right now if you don't provide a form helper key in React, you'll end up with a key of `'undefined-form-data'`, which is weird. This PR cleans that up.

Improve react form helper keys

---

packages/inertia-vue3/src/link.js

This PR fixes an error triggered when you create self-closing `inertia-link` component, which sets `slots` to null:
```vue
<inertia-link class="absolute inset-0 z-10" :href="route('dashboard.edit', dashboard).url()" />
```

Fix inertia-link crashing when self-closing

---

packages/inertia-vue/src/form.js
packages/inertia-vue3/src/form.js
packages/inertia/src/inertia.js

Resolves #389
This PR fixes a tricky, edge case issue with the form helpers, where the `preserveState` and `preserveScroll` callbacks are evaluated *before* the page is rendered, props are swapped, and the `onError` and `onSuccess` callbacks are evaluated. The result is that if you have local state (such as the form helper) that updates based on the `onError` and `onSuccess` callbacks, that state will not be updated on time for the `preserveState` and `preserveScroll` callbacks.
```js
preserveScroll: () => this.form.hasErrors, // will have value prior to submit, not after submit
preserveState: () => this.form.hasErrors, // will have value prior to submit, not after submit
```
One solution is to simply not use the local state in this situation, and just use the `page` object that's …

Add "onBeforeRender" callback

---

packages/inertia-vue3/src/useForm.js

Fixes #552 (properly lol)
Fixes #582
This fixes an issue in the Vue 3 form helper where the remember functionality breaks when the form helper data includes an array, and I suspect an object.

Fix remember functionality in Vue 3 form helper

---

packages/inertia-vue3/src/app.js

Fixes #579
This update prevents Vue 3 from throwing a warning when setting an array of layouts.

Use function for layout child in Vue 3 adapter

---

packages/inertia-vue3/src/remember.js

This is a follow-up for the PR https://github.com/inertiajs/inertia/pull/587.
Personally, I use a custom Form component, instead of using the built-in form helper.
My custom component has the `remember` property, which leads to the same issue that is solved for the built-in form helper.
With this change, it works well now. I guess this does not affect any other part of the code.

Fix remember

---

packages/inertia-vue3/src/useRemember.js

Continuing the "clone deep" changes from #587 and #591, this updates the `useRemember` hook to use `cloneDeep` as well.

Update Vue 3 useRemember hook to use cloneDeep

---

packages/inertia-react/src/useForm.js
packages/inertia-svelte/src/useForm.js
packages/inertia-vue/src/form.js
packages/inertia-vue3/src/useForm.js

This fixes a bug with the form helper where you get an error if you don't pass any data. Previously this was possible, and is useful for things like delete forms.
```js
// Breaks (but now fixed)
let form = useForm()
// Works
let form = useForm({})
```

Fix bug when creating a form helper without passing a data object

---

packages/inertia-react/src/App.js

While the `useEffect` dependencies are correct in theory, they're a pain for hot module replacement with React.
When HMR kicks in, the effect gets cleaned up and `Inertia.init` gets called again. This causes the initial page to be rendered instead of the current one.
There might be a cleaner way to solve this along the road, but I can't think of any better, and don't see any practical downsides of this change.

React HMR fix

---

packages/inertia-react/src/useForm.js
packages/inertia-svelte/src/useForm.js
packages/inertia-vue/src/form.js
packages/inertia-vue3/src/useForm.js

This PR adds a new `form.cancel()` method to the form helper. This saves you from having to manually track the cancel token.
```js
data() {
return {
cancelToken: null,
form: this.$inertia.form({ ... }),
}
},
this.form.post('/users', {
onCancelToken: (cancelToken) => (this.cancelToken = cancelToken),
})
// Cancel the visit
this.cancelToken.cancel()
```
```js
data() {
return {
form: this.$inertia.form({ ... }),
}
},
this.form.post('/users')
// Cancel the visit
this.form.cancel()
```
This PR also removes the `onSuccess` and `onFinish` callbacks, and uses the `onBeforeRender` callback for everything. This was needed, since I noticed that `processing` was showing stale data when used in a visit callback (same problem as #410).

Add cancel support to form helper

---

packages/inertia-react/index.d.ts

The way `InertiaLinkProps` is currently typed, causes `data` and `headers` to not accept any value, as it's typed as `string` in `React.AllHTMLAttributes`, and as `object` in `InertiaLinkProps`.
As is already done for `onProgress`, we should omit all the props Inertia is using, to avoid any other conflicts in the typing.
Credits to @sebastiandedeyne for the idea :)

fix InertiaLinkProps typing

---

packages/inertia-vue/src/remember.js
packages/inertia-vue3/src/remember.js

This PR fixes #620 by checking whether a value is `null` before the `typeof this[key].__remember === 'function'` check. After making this change, the remember functionality started working as expected again.
Quick note: I had a look around the codebase to see if the optional chaining operator (`?.`) syntax was used anywhere but couldn't see it so didn't use it here. The syntax could however be cleaned up a bit by using:
```js
const hasCallacks = typeof this[key]?.__remember === 'function' && typeof this[key]?.__restore === 'function'
```
Let me know if there are any questions or if any changes are needed.

Fix 'remember' issue for null values

---

packages/inertia-vue/src/form.js
packages/inertia-vue3/src/useForm.js
packages/inertia/src/inertia.js

This PR reverts a previous change (#410) that added a new `onBeforeRender()` event, used by the Vue 2 and Vue 3 form helpers to set form state earlier in the visit lifecycle. As it turns out, this creates other issues, such as the page props being out of date when `form.processing` returns back to `false`.
The entire motivation with adding `onBeforeRender()` was to simplify this:
```js
preserveScroll: (page) => Object.keys(page.props.errors).length > 0,
preserveState: (page) => Object.keys(page.props.errors).length > 0,
```
To this:
```js
preserveScroll: () => this.form.hasErrors,
preserveState: () => this.form.hasErrors,
```
Instead of solving the problem that way, I've introduced a new option to `preserveScroll` and `preserveState` specifically for preserving the scroll/state when there …

Remove "onBeforeRender" event and add "errors" option to preserveScroll and preserveState

---

packages/inertia-vue3/index.d.ts

Some change is refer to [Inertia React Adapter's type definition file](https://github.com/inertiajs/inertia/blob/master/packages/inertia-react/index.d.ts)
Update list:
* Rename Form type to `InertiaForm` and `InertiaFormProps`
* Rename `Data` type to `TForm`
* Change `errors` property type to `Record`
* Remove `serialize()` and `unserialize()` methods
* Add `useForm()` overload
* Code formatting

Update vue3 adapter type definition file

---

packages/inertia-react/src/useForm.js
packages/inertia-svelte/src/useForm.js
packages/inertia-vue/src/form.js
packages/inertia-vue3/src/useForm.js

This PR fixes an issue with the form helper where the `processing` and `progress` states were out of date when using custom event callbacks:
```js
this.form.post('/users', {
onSuccess: () => {
console.log(this.form.processing)
// Before: true
// After: false
},
})
```
Previously we set these values in the `onFinish` event callback, which runs after the `onSuccess`, `onError` callbacks. With this update, we now set these values within the `onSuccess`, `onError` and `onCancel` callbacks, so that they are immediately available.

Fix "processing" and "progress" form helper state

---

packages/inertia-vue3/src/link.js

Closes #636
For some reason the Vue 3 adapter shows the `<inertia-link>` component as an anonymous component in the dev tools, even though we're registering it the same way as the Vue 2 adapter. This PR adds an explicit component name to fix that.

Add name to the Inertia link component in the Vue 3 adapter

---

packages/inertia-vue3/src/app.js

If you're using the Vue 3 adapter, and are using the new fragments feature (where you can have multiple root nodes in a component), you'll often get this warning shown:
> Extraneous non-props attributes (errors) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.
This is because Vue has received the default `errors` prop from the server (or any other shared prop), but isn't sure what root node to "apply" it to. You can disable this warning by wrapping your page component in a `<div>`. However, this also isn't a great solution, since Vue will now try to render the `errors` prop as an attribute on this element:
```html
<div errors="[object Object]">
</div>
```
You can correct this issue by *always* accepting the `errors` …

Disable page attribute inheritance in Vue 3 adapter

---

packages/inertia-react/src/useForm.js
packages/inertia-svelte/src/useForm.js
packages/inertia-vue/src/form.js
packages/inertia-vue3/src/useForm.js

Closes #670 #657
This PR updates the form helpers to reset the `processing` and `progress` states in the event that the submission results in an exception (error).

Reset form helper on visit exception

---

packages/inertia/index.d.ts

Data property should be available with `reload` because it's calling `visit` behind the scense
```js
reload(options = {}) {
return this.visit(window.location.href, { ...options, preserveScroll: true, preserveState: true })
},
```
```ts
visit: (
url: string,
options?: VisitOptions & { data?: object }
) => Promise<void>
```

Add data to reload visit options

---

packages/inertia-react/index.d.ts

This PR add `const App` type that has been lacked in `inertia-react`. The same type definition has already been defined in `inertia-vue`. Please see the following code:
https://github.com/inertiajs/inertia/blob/bf5a17e2cff21d0caec85b7c4ee8fbacd63c4500/packages/inertia-vue/index.d.ts#L78
It also solves the issue: https://github.com/inertiajs/inertiajs.com/pull/181 without changing the document.

Add `const App` type in inertia-react.

---

packages/inertia/src/files.js
packages/inertia/src/formData.js
packages/inertia/src/inertia.js

This change makes the `hasFiles` function able to determine if files are included in a `FormData` object.
I'm currently developing a project that uses [an unofficial port of Inertia](https://github.com/Nothing-Works/inertia-aspnetcore) in an ASP.NET Core environment. To make sure file lists are correctly translated into view models, i need to make sure they are added with the same name without indices attached to the name, as illustrated below:
```js
const formData = new FormData();
formData.append("files", new File([], "file1"));
formData.append("files", new File([], "file2"));
```
In the current version of Inertia, i *can* add an object like the above as a parameter to a visit, but due to Inertia not knowing there are files included in the form, no progress events are being fired, …

Extend hasFiles to support FormData

---

packages/inertia-react/package.json
packages/inertia-react/src/useForm.js
packages/inertia-svelte/package.json
packages/inertia-svelte/src/useForm.js
packages/inertia-vue/package.json
packages/inertia-vue/src/form.js
packages/inertia-vue3/package.json
packages/inertia-vue3/src/useForm.js

This PR adds a new `isDirty` property to the form helper, which indicates whether the current form data is different from the default form data provided. This can be used to show a "there are unsaved form changes" message to the user.
With this update, we now automatically replace the default form data with the current form data on successful submit. This is important, since we compare the default form data with the current form data to determine if the form is dirty. If we didn't update the default form data, the form would remain dirty even after submitting it.
https://user-images.githubusercontent.com/882133/117467251-82e8ab80-af21-11eb-86de-0390981cd4b1.mov

Add form helper `isDirty` feature

---

packages/inertia-react/src/App.js
packages/inertia-vue/src/app.js
packages/inertia-vue3/src/app.js
packages/inertia/src/head.ts

This PR updates the Vue 2, Vue 3 and React adapters to all use an `onHeadUpdate()` prop for handling `<head>` updates in SSR mode. It also tweaks the `createHeadManager()` method to require an `onUpdate()` callback, where previously this was set using `headManager.onUpdate(callback)`.

Unify `onHeadUpdate` prop across adapters

---

packages/inertia-react/src/App.js
packages/inertia-vue/src/app.js
packages/inertia-vue3/src/app.js

Resolves #696
This PR adds a new `initialComponent` prop to the Vue 2, Vue 3 and React adapters. The primary purpose of this prop is for apps using SSR.
When running the app in Node, you no longer need to provide a `resolveComponent` prop. Instead, you now just provide a `initialComponent` instead.
```diff
- resolveComponent: (name) => require(`./Pages/${name}`).default,
+ initialComponent: require(`./Pages/${request.body.component}`).default,
```
When running an SSR-enable app in the browser, when using code-splitting, you can also pass in an `initialComponent` prop to ensure that client-side hydration works. Otherwise, if you don't do this, the first client-side render will not have the component on time, and will render blank, and hydration will fail.

Initial component

---

packages/inertia-react/src/createInertiaApp.js
packages/inertia-react/src/index.js
packages/inertia-svelte/src/createInertiaApp.js
packages/inertia-svelte/src/index.js
packages/inertia-vue/src/createInertiaApp.js
packages/inertia-vue/src/index.js
packages/inertia-vue3/src/createInertiaApp.js
packages/inertia-vue3/src/index.js

This PR adds a new `createInertiaApp()` method to the adapters, making Inertia easier to configure. Here is an example using the Vue 2 adapter:
```js
import Vue from 'vue'
import { createInertiaApp } from '@inertiajs/inertia-vue'
createInertiaApp({
resolve: name => import(`./Pages/${name}`),
setup({ el, app, props }) {
new Vue({
render: h => h(app, props),
}).$mount(el)
},
})
```
TODO:

Add createInertiaApp() method

---

packages/inertia-react/src/Head.js
packages/inertia-vue/src/head.js
packages/inertia-vue3/src/head.js
packages/inertia/src/head.ts

This PR updates the `<inertia-head>` to use `head-key` instead of `inertia` when setting a unique key to prevent duplicate tags. Using "inertia" for this was confusing, as it doesn't really indicate its purpose at all. The term "key", on the other hand, is well known in client-side frameworks for identifying uniqueness. We would have just used `key`, but Vue uses this internally, so that wasn't possible.
```html
<inertia-head>
<meta head-key="description" name="description" content="This is the default description" />
</inertia-head>
<inertia-head>
<meta head-key="description" name="description" content="This is a page specific description" />
</inertia-head>
```

Rename `<inertia-head>` "inertia" key to "head-key"

---

packages/inertia-vue/index.d.ts
packages/inertia/src/index.ts
packages/inertia/src/types.ts

While working with the newest version I noticed several incorrect typings. If you agree, these types would also need to be adapted in `vue3` and `react` package.
Also, currently, types can only be imported from the types file directly but it would be great to have them all exported on package level.

fix: fix types

---

packages/inertia-vue3/src/head.js

Fixes #715
Right now if you include a `<slot />` within `<inertia-head>`, it throws an error, since the head component doesn't know how to render a fragment. This fixes that by checking to see if a fragment was provided, and if one was, uses its children instead.

Add support for fragments in Head component in Vue 3 adapter

---

packages/inertia/src/router.ts

Fixes #716
This PR updates Inertia core to use `preserveState: true` by default when rendering the initial page. Previously this didn't matter, because the initial page component didn't render until `Inertia.init()` was run. However, recently, to accommodate SSR (server-side rendering), we updated the adapters to render the initial page component on first render. This causes two renders, since it renders again when `Inertia.init()` run. By setting `preserveState` to `true`, we prevent the double render from happening, since the page component key does not change.

Fix double render on initial page load

---

packages/inertia-svelte/src/createInertiaApp.js

I am using Rollup and with the current version of the Svelte adapter it aborts with this error:
```
[!] Error: Could not resolve './App' from node_modules\@inertiajs\inertia-svelte\src\createInertiaApp.js
```
This change fixes it.

Fix import of App.svelte in createInertiaApp.js

---

packages/inertia-vue3/src/head.js

Resolves #731
This PR adds an addition check to the `<inertia-head>`, needed when running Vue 3 in production. Oddly the vnodes are different in production than development.

Fix issue with `<inertia-head>` component in production

---

packages/inertia-vue3/src/app.js

Resolves #733
This change is similar to #681, where unused page props (that are passed to the layout component as a result of #602) are being actually rendered as attributes in the Vue 3 adapter. For example, the `errors` prop:
```html
<div errors="[object Object]">
</div>
```
This PR fixes this by automatically disabling attribute inheritance on the layout components by setting `inheritAttrs` to `false`.

Disable layout attribute inheritance in Vue 3 adapter

---

packages/inertia-react/src/useForm.js

This PR fixed the issue where `recentlySuccessful` property of Inertia's React form helper is changed to false after 2 seconds, even after the component containing the state is unmounted, resolving the error that React state update can't be performed on an unmounted component.
Currently, the property is changed with:
```javascript
recentlySuccessfulTimeoutId.current = setTimeout(() => setRecentlySuccessful(false), 2000)
``` 
This PR implements the existing mount check before the state update.
```javascript
recentlySuccessfulTimeoutId.current = setTimeout(() => {
if (isMounted.current) setRecentlySuccessful(false)
}, 2000)
```
I believe this fixes #761.

Fixed state change error after unmount

---

packages/inertia/src/types.ts

with the new typescript types addition, Its not possible to send the array values to the form data, for example the below code outputs the type error "Type 'CollectionCondition[]' is not assignable to type 'string'."
```ts
export interface CollectionCondition {
id: number;
field: CollectionField;
criteria: string;
value: string;
}
export interface Collection {
id: number;
name: string;
determiner: CollectionDeterminer;
conditions: Array<CollectionCondition>;
}
const { data, setData } = useForm<Collection>({
id: 1,
name: "Summer collection",
type: "manual",
determiner: "all",
conditions: [],
});
Inertia.post(url, data, {
onSuccess: () => {
Inertia.reload();
},
});
```
with the changes adding Array<any> type in FormDataConvertible type we can pass the array values to the form.

allow array values to be passed in form

---

packages/inertia/src/types.ts

This allows adding an optional type to the `Page` interface to create type safety for shared props.
Example:
```typescript
// before
const { foo } = usePage().props; // no type safety :-(
// now
type MyPage = Page<{foo: string}>;
const { foo } = usePage<MyPage>().props; // yeah type safe 'foo'
```

Add generic argument to Page type to allow for shared props typing

---

packages/inertia/src/router.ts

This preserves types, while eliminating options rendered unusable due to the method overriding them, all while not adding new types to keep updated in 7 other places.

Type options param for visit shortcuts.

---

packages/inertia-vue/index.d.ts
packages/inertia-vue3/index.d.ts

Update list in vue 2/3 type definition:
* `InertiaApp` type
* `createInertiaApp()` type
* `usePage()` type in vue 3
* head types
* Expose all types (reference by #741)
* Remove `ProgressEvent` type
* Fix `InertiaFormProps` type
Add `GlobalComponents` interface in Vue 3 types to support global components of [Volar](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar).

Update Vue 2/3 adapter type definition file 

---

packages/inertia-react/src/useForm.js

**ISSUE:** 
when resetting parts of form fields like: `reset('password')`, all other left fields data gets removed.
this is because the [`initialValue`](https://github.com/inertiajs/inertia/blob/0fb6765af94bb571a907b93df1f5b7b238017df1/packages/inertia-react/src/useForm.js#L157) of the `Array.reduce()` is set to blank `{}` so the `setData` hook keeps only the fields data that were mentioned in `reset()` method called by user.
**SOLVE:**
if the `initialValue` is set to the current field values as a copy `{...data}` then it can be fixed ✌

fix resetting partial form data removing all other fields - REACT `useForm`

---

packages/inertia-react/index.d.ts

Just adding `isDirty` type definition for the `useForm` hook in the React adapter.

Add `isDirty` definition for `useForm` hook

---

packages/inertia-vue/index.d.ts
packages/inertia-vue3/index.d.ts

Update list:
* Update Link, Head type
* Add title callback type in createInertiaApp()
---
Register components:
*resources/js/app.d.ts*
```js
...
import { createInertiaApp, Link, Head } from '@inertiajs/inertia-vue3'
createInertiaApp({
...
setup({ el, app, props, plugin }) {
createApp({ render: () => h(app, props) })
.use(plugin)
.component('InertiaLink', Link)  // InertiaLink component
.component('InertiaHead', Head)  // InertiaHead component
.mount(el)
},
})
```
Add global components typing with [Volar](https://github.com/johnsoncodehk/volar):
*resources/js/shims-vue.d.ts*
```ts
declare module 'vue' {
export interface GlobalComponents {
InertiaLink: typeof import('@inertiajs/inertia-vue3').Link
InertiaHead: typeof import('@inertiajs/inertia-vue3').Head
}
}
export {}
```
Now can use the …

Update Vue 2/3 adapters types

---

packages/inertia/src/router.ts

While using Inertia the following error sometimes pops up:
```
Uncaught (in promise) TypeError: Cannot read property 'top' of undefined
at router.ts:89
at NodeList.forEach (<anonymous>)
at e2.n2.restoreScrollPositions (router.ts:88)
at router.ts:401
```
Relating to this line: https://github.com/inertiajs/inertia/blob/master/packages/inertia/src/router.ts#L88
I am not entirely sure why the scroll regions are not properly saved sometimes so perhaps this does't fix the underlying issue, but it wouldn't hurt to have a little sanity check here that checks if the value is present before applying it.

Check if scroll region's position is available before restoring

---

packages/inertia/src/router.ts

This PR changes the behaviour of the initial `navigate` event to be fired *after* the initial component has been resolved. This is similar to the behaviour on subsequent visits in Inertia.
The use case I have for this is that I want to set a value to be remembered after a `navigate` event. However due to the event being fired before the component has been resolved the history state will be overwritten.
```js
Inertia.on('navigate', () => {
Inertia.remember(Date.now(), 'key');
});
```
Now if you'd check the history after the component has been loaded, you see the `rememberedState` is empty.
```js
window.history.state.rememberedState
> {}
```

fire navigate event after resolving initial component

---

packages/inertia-react/src/Link.js
packages/inertia-svelte/src/link.js
packages/inertia-vue/src/link.js
packages/inertia-vue3/src/link.js

This PR updates the `<Link>` component in all four adapters to gracefully handle the situation where the `href` value is set to `null`. This is actually more common (ie. the Laravel pagination links), which causes a fatal error to occur, since the `mergeDataIntoQueryString()` method doesn't know what to do with `null` or `undefined` values.

Fix links with `null` href values

---

packages/inertia-react/index.d.ts

Proposes a fix for a wrong type used for `method` argument in `InertiaFormProps.submit` method, which actually should be one of `Inertia.Method` enum values, or maybe a union type like:
```ts
type submitMethod = 'get' | 'patch' | 'post' | 'put' | 'delete'
```
fixes #837

Fix wrong type in InertiaFormProps.submit method

---

packages/inertia-react/index.d.ts

This PR fixes an incorrect type for the resolve method on the createInertiaApp.
Currently this is typed as `resolve(name: string): PageResolver` since `PageResolver` is already a function this is wrongly defined as a "factory function" and this will cause issues, e.g.
```
resolve: (name) => import(`./Pages/${name}`) as React.ReactNode
```
results in
```
> No overload matches this call.
Overload 1 of 2, '(options: InertiaAppOptionsForCSR<PageProps>): Promise<CreateInertiaAppSetupReturnType>', gave the following error.
Type 'ReactNode' is not assignable to type 'PageResolver'.
Type 'undefined' is not assignable to type 'PageResolver'.ts(2769)
index.d.ts(106, 5): The expected type comes from the return type of this signature.
```
The solution is to remove the parameter from the `resolve` …

Fix incorrect type for resolve option for React's createInertiaApp

---

packages/inertia/src/url.ts

Right now `@inertiajs/inertia` detects whether a URL has `host` or not by simply checking if it includes the word `http`. Which causes an error when using a relative URL that includes the word `http` (see issue #963). This PR attempts to solve the issue by checking if the URL starts with `http://` or `https://`.

fix: system to check whether a URL has host

---

packages/inertia-react/index.d.ts

Hello,
This PR fix the return value for `useForm` methods (`submit`, `get`, `patch`, `post`, `put` and `delete`) because that methods need return `void` instead `Promise<void>` (that methods is not promise).
Thanks.

Fix incorrect type for useForm methods

---

packages/inertia-vue3/index.d.ts

The result of `resolveComponent` can also be asynchronously.

fix: use promised return type

---

packages/inertia-react/src/Link.js
packages/inertia-vue/src/link.js
packages/inertia-vue/tests/cypress/integration/links.test.js
packages/inertia-vue3/src/link.js

Console alert messages still use the old `inertia-link` syntax. This PR replaces them with the new syntax.
(I hope I didn't break anything! :pray: )

Replace `inertia-link` with `Link` in console messages

---

packages/inertia-react/index.d.ts
packages/inertia/src/types.ts

`useForm`'s `progress` property is typed as a number in react package. I noticed it is actually a 
[`ProgressEvent`](https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent) extended with the `percentage` in:
https://github.com/inertiajs/inertia/blob/1dc7fef4cdbd7c506b7213235a98ddb21d4f4db9/packages/inertia/src/router.ts#L287-L289
Based on this, I propose a new `Inertia.Progress` type so it can be used by the other packages.

Fix useForm progress type

---

packages/inertia-vue3/index.d.ts

Hello,
Thanks for the hard work !
I have recently updated the packages and noticed a regression with Vue3 types here https://github.com/inertiajs/inertia/commit/82c927ff6640a5ecc7b39f32fe2f9ae9a62ae953#diff-68769ed64e5114a6520e6d1a040a8fc8a01230710d0daaa045949608398e7f01
I made this PR as it hasn't changed in Vue Docs (https://v3.vuejs.org/guide/typescript-support.html#typing-refs). Don't hesitate to ask for changes ! I have also opened a corresponding issue https://github.com/inertiajs/inertia/issues/850.
Have a nice day.

fix: declare @vue/runtime-core instead of vue for vue3

---

packages/inertia-react/src/Link.js
packages/inertia-svelte/src/link.js
packages/inertia-vue/src/link.js
packages/inertia-vue/tests/app/Pages/Links/Data/Object.vue
packages/inertia-vue/tests/app/Pages/Visits/Data/Object.vue
packages/inertia-vue/tests/cypress/integration/links.test.js
packages/inertia-vue/tests/cypress/integration/manual-visits.test.js
packages/inertia-vue3/src/link.js
packages/inertia/src/router.ts
packages/inertia/src/types.ts
packages/inertia/src/url.ts

This PR enables the ability to provide a different method of formatting query string when making GET-requests with URL params (data).
It allows for the following options, available with _all_ Inertia visit types. (The default is the "brackets" type):
```html
<Link href="/foo" :data="{ a: ['b', 'c'] }" queryStringArrayFormat="brackets">Example</Link>
<Link href="/foo" :data="{ a: ['b', 'c'] }" queryStringArrayFormat="indices">Example</Link>
```

Query String: Allow different 'Array' formatters

---

packages/inertia-react/src/useForm.js

Gives more flexibility and options to customise the errors displayed when using other API calls or methods to update the form (ie. not alway 100% inertia requests)

Expose "setErrors" method in useForm

---

packages/inertia-react/index.d.ts
packages/inertia-react/src/useForm.js
packages/inertia/src/router.ts

Useform did not work in combination with useRemember. The types were wrong & the function used an odd way to trigger the useRemember function. This adds an extra param to the useForm to add an rememberkey (just like useRemember works).
You can now add an extra param to trigger the useRemember function.
If you do not add the param, it will use useState instead of useRemember.
```
const initialValues = {
first_name: '',
last_name: ''
}
const { data, setData } = useForm(initialValues, 'registerForm');
```
RememberedState also threw an error mentioned in https://github.com/inertiajs/inertia/issues/866 , made this optional to fix it.

fix useForm with useRemember

---

packages/inertia-react/index.d.ts
packages/inertia-react/src/useForm.js
packages/inertia-svelte/src/useForm.js
packages/inertia-vue/index.d.ts
packages/inertia-vue/src/form.js
packages/inertia-vue/tests/app/Pages/FormHelper/Errors.vue
packages/inertia-vue/tests/cypress/integration/form-helper.test.js
packages/inertia-vue3/index.d.ts
packages/inertia-vue3/src/useForm.js

This PR adds the ability to set form errors manually, which can be useful in situations where you're (for example) using third-party API calls to upload a file in the background, and want to show the error as part of your Inertia form. Other uses include third-party client-side JS validation libraries, or just custom checks such as a network status check.
```js
const form = this.$inertia.form({ 
username: 'reinink',
password: '',
});
// Single error
form.setError('username', 'This username is not available.');
// Multiple errors
form.setError({
username: 'This username is already taken.',
password: 'The password field cannot be left blank.'
});
```

Add "setErrors" method to Form helper

---

packages/inertia-vue/index.d.ts
packages/inertia-vue/src/form.js
packages/inertia-vue3/index.d.ts
packages/inertia-vue3/src/useForm.js

Currently the `form.reset()` does not allow the users to reset the `form.data()` with their desired values. This PR adds a `form.resetWith()` function that accepts an object as the first (and only) argument and resets the form data with the given values.
Ex:
```js
// form data before:
// {
//   name: 'avril',
//   email: 'avril@example.com'
// }
form.resetWith({
email: 'johny@example.com'
})
// after:
// {
//   name: 'avril',
//   email: 'johny@example.com'
// }
```

Add form.resetWith() function to vue packages

---

packages/inertia-react/index.d.ts
packages/inertia-react/src/useForm.js
packages/inertia-svelte/src/useForm.js
packages/inertia-vue/index.d.ts
packages/inertia-vue/src/form.js
packages/inertia-vue/tests/app/Pages/FormHelper/Data.vue
packages/inertia-vue/tests/cypress/integration/form-helper.test.js
packages/inertia-vue3/index.d.ts
packages/inertia-vue3/src/useForm.js

This PR adds a "defaults" method to the Form Helper, allowing people to reset the default values without initializing the form. Do note that it does not reset the form, but only changes the defaults that are used when the form (or some of it's fields) are reset.
Signatures:
```js
setDefaults()
setDefaults(field: string, value: string)
setDefaults(fields: object)
```
Here's some examples of how you can use this:
```js
export default {
data() {
return {
form: this.$inertia.form({
email: 'johndoe@example.com',
password: 'secret',
remember: false,
}),
}
},
methods: {
submit() {
this.form.post('/login', {
onSuccess: () => {
// Set the current values as the new defaults
this.form.defaults()
// Only change the email field
this.form.defaults('email', 'foo@example.com')
// Change the defaults to …
```

Add "defaults" method to Form helper

---

packages/inertia-react/CHANGELOG.md
packages/inertia-svelte/CHANGELOG.md
packages/inertia-vue/CHANGELOG.md
packages/inertia-vue3/CHANGELOG.md
packages/inertia/CHANGELOG.md

This PR adds CHANGELOG.md files to every package in this repository, similar to [how the team over at TailwindCSS handles their changes](https://github.com/tailwindlabs/tailwindcss/blob/master/CHANGELOG.md). 
The main benefit of this, is that it makes the tracking of (breaking) changes and additions easier, which in turn makes releases easier, as well as that it allows for @reinink and I to go over certain things faster when we catch up on what's happening

Add Changelog files

---

packages/inertia/src/router.ts

When using Inertia's form helper with it's remember functionality during SSR, it'll throw an error in the Console.
```js
someForm: this.$inertia.form('someFormRememberKey', {
key: 'value',
})
```
```
[Vue warn]: Error in data(): "ReferenceError: window is not defined"
found in
---> <Anonymous>
<Anonymous>
<Anonymous>
<Inertia>
<Root>
ReferenceError: window is not defined
at e.n.restore (/Users/claudiodekker/Code/demo/node_modules/@inertiajs/inertia/dist/index.js:1:13330)
at e.s [as form] (/Users/claudiodekker/Code/demo/node_modules/@inertiajs/inertia-vue/dist/index.js:1:530)
at VueComponent.data (/Users/claudiodekker/Code/demo/public/js/ssr.js:1:468776)
at getData (/Users/claudiodekker/Code/demo/node_modules/vue/dist/vue.runtime.common.dev.js:4745:17)
at initData …
```

Forms: 'ReferenceError: window is not defined'

---

packages/inertia/CHANGELOG.md
packages/inertia/src/types.ts

Fixes #951
Certain events always required 'bool' return types, while 'void' (falsy) should be possible too

Events: Allow 'void' return types

---

packages/inertia-react/src/App.js
packages/inertia-vue/src/app.js
packages/inertia-vue3/src/app.js
packages/inertia/src/head.ts

This PR fixes the `<head>` title tag not defaulting to the `createInertiaApp` when the `title` callback is defined.

Fix default <head> title tag

---

packages/inertia-react/index.d.ts
packages/inertia-react/src/App.js
packages/inertia-react/src/createInertiaApp.js
packages/inertia-svelte/src/App.svelte
packages/inertia-svelte/src/createInertiaApp.js
packages/inertia-vue/index.d.ts
packages/inertia-vue/src/app.js
packages/inertia-vue/src/createInertiaApp.js
packages/inertia-vue/src/link.js
packages/inertia-vue3/index.d.ts
packages/inertia-vue3/src/app.js
packages/inertia-vue3/src/createInertiaApp.js
packages/inertia/src/router.ts
packages/inertia/src/types.ts

This PR adds a global hook that's executed prior to any visit. 
This allows for modifying headers etc. in a single place, instead of having to apply them globally.
While the URL itself is only available to conditionally apply actions (e.g. on a specific path/prefix) and **cannot be modified**, the options object itself can be adjusted. This options object essentially reflects your Visit options (everything available from an `$inertia.get('/url', options)` etc.).
```js
createInertiaApp({
// ...
visitOptions(options, url) {
options.headers = {
'some-global-header': 'some-global-header-value'
}
return options
}
})
```

Add Global "Visit" Options Hook

---

packages/inertia/package.json
packages/inertia/src/router.ts

Axios has published several new versions including security fixes https://github.com/axios/axios/releases

Update axios version

---

packages/inertia/package.json

Bumps Axios to the latest 0.27.x release. As far as I can see there's no impact for Inertia
Release notes:
- [v0.27.0](https://github.com/axios/axios/releases/tag/v0.27.0)
- [v0.27.1](https://github.com/axios/axios/releases/tag/v0.27.1)
- [v0.27.2](https://github.com/axios/axios/releases/tag/v0.27.2)

Bump Axios to ^0.27.0

---

packages/inertia/src/types.ts

Doing a reload and sending across `undefined` explicitly for a key in data works, it will remove it from the url.
But the type doesn't allow it
E.g. the following works in straight js
```js
// page is /hello
Inertia.reload({data: {test: 5}});
//page is now /hello?test=5
Inertia.reload({data: {test: null}});
//page is now /hello?test=
Inertia.reload({data: {test: undefined}});
//page is now /hello
```

Add `undefined` as a valid option FormDataConvertable

---

packages/inertia/src/router.ts

Scroll position can fail to update in Firefox when setting it via `element.scrollTop` and `element.scrollLeft`. Change to preferring `element.scrollTo` with a fallback for the previous method to ensure backwards compatibility.
Resolves #1079

Change to preferring element.scrollTo

---

packages/inertia-vue3/index.d.ts

- Reverted `index.d.ts` file (editor glitch: https://twitter.com/reinink/status/1559854459467055108)
- Removed `visitOptions` from `CreateInertiaAppProps` type
- Changed `VisitParams` to `VisitOptions`, due to latest updates in https://github.com/inertiajs/inertia/commit/1d06b015275b791c9e0bf40830d8552f80a038b8

Revert index.d.ts in vue3 package, switch to VisitOptions

---

packages/vue3/index.d.ts

This PR fixes TypeScript declarations for Vue 3 package.
- added `router` export
- replaced `app` to `App` in the `setup` method

Fix: TypeScript declarations

---

package.json
packages/svelte/src/App.svelte
packages/svelte/src/Link.svelte
packages/svelte/src/Render.svelte
packages/svelte/src/link.js

This PR brings a bunch of improvements to the `use:inertia` action and `<Link />` component.
It was a mistake to dispatch the `click` event with `createEventDispatcher` from the action in first place. Its use is [intended for components](https://svelte.dev/docs#template-syntax-component-directives). We ran into an edge-case bug because of this in our own app.
The element where `use:inertia` is used on can still have an `on:click` handler or an event forwarder.
This allows you to listen to Inertia event callbacks the Svelte way when using `use:inertia`.
```svelte
<button
use:inertia={{ method: 'PUT', href: '/posts' }}
type="button"
on:start={({ detail }) => console.log(detail.visit)}
on:finish={({ detail }) => console.log(detail.visit)}
>
Create post
</button>
```
All [event …

Improve Svelte use:inertia and <Link />

---

packages/vue3/src/app.ts
playgrounds/vue3/resources/js/Components/Layout.vue

This PR simplifies the `usePage()` hook in the Vue 3 adapter. We use to run `computed()` on each value in the `page` object (in the root `<App>` component):
```js
export function usePage() {
return {
props: computed(() => page.value.props),
url: computed(() => page.value.url),
component: computed(() => page.value.component),
version: computed(() => page.value.version),
}
```
In hindsight I honestly don't know why we did this. As far as I can tell you still always need to use `usePage()` in conjunction with a `computed()` call within your own components anyway, so this is redundant. Here's what you need to do today:
```js
import { computed } from 'vue'
const appName = computed(() => usePage().props.value.appName)
//  ^
//  |- I hate that this .value is required
```
This would be worth it …

Simplify `usePage()` hook in Vue 3 adapter

---

packages/core/package.json
packages/core/src/router.ts
packages/core/src/types.ts
packages/vue2/tests/cypress/integration/events.test.js
packages/vue2/tests/cypress/integration/form-helper.test.js

This PR updates axios to 1.x.
As part of this update we've replaced the internal `cancelToken` handling with the new `AbortController` handling available in the newer versions of axios, as cancel tokens have been deprecated. However, the external API (`onCancelToken()` visit callback) has not changed for backwards compatibility reasons.
Also included with this update is a fancy new `router.cancel()` method that lets you easily cancel the currently active visit, effectively removing the need to ever use the `onCancelToken()` visit callback again.
```js
import { router } from '@inertiajs/vue3'
router.cancel()
```

Update axios to 1.x

---

packages/core/package.json
packages/react/package.json
packages/react/tsconfig.json
packages/vue2/package.json
packages/vue2/tsconfig.json
packages/vue3/package.json
packages/vue3/tsconfig.json
playgrounds/vue3/resources/js/ssr.ts

The "exports" field of the package.json was misused for the type-declarations. Also, the type-declarations of secondary entrypoint (server.ts) of the platform packages was not generated.
Docs:
- https://2ality.com/2021/06/typescript-esm-nodejs.html#mapping-a-directory-to-a-file
- https://dev.to/binjospookie/exports-in-package-json-1fl2

Fix: export types correctly

---

packages/vue2/src/createInertiaApp.ts

Uppercase `App` in `setup` function props in CreateInertiaAppProps interface.

Fix CreateInertiaAppProps interface in Vue2 package

---

packages/core/src/types.ts
packages/react/src/createInertiaApp.ts
packages/vue3/src/app.ts
playgrounds/vue3/resources/js/Components/Layout.vue

When converting the adapters to TypeScript, I forgot to copy over the existing type definition for `usePage` which used a generic.
This PR attempts to restore this, however, I can't currently get it to build.
Fixes #1381

Restore Vue 3 `usePage` generic type

---

packages/react/src/Head.ts

According to the [documentation ](https://inertiajs.com/title-and-meta#head-extension)you can extend Inertia's Head component.
Here is the example from the docs.
```JavaScript
// AppHead.js
import { Head } from '@inertiajs/react'
const Site = ({ title, children }) => {
return (
<Head>
<title>{title ? `${title} - My App` : 'My App'}</title>
{children}
</Head>
)
}
export default Site
```
And then use that extended component like this:
```JavaScript
import AppHead from './AppHead'
<AppHead title="About">
```
**The problem**
As you can see AppHead can receive children. But if you try to pass more than one child to that extended Head component, you will get an error in the console:  `TypeError: e.props is undefined`
Here is the example of such usage that throws an error
```JavaScript
import …
```

Fix props is undefined in extended Inertia's Head

---

packages/react/src/Head.ts

PR for Issue #1437 
In React 18, the `React.FC` interface removed the `children` prop. Therefore, as seen in the issue, any use of children in Inertia `Head` component will produce a type error. The use of children in this component is required to set `meta` tags as shown in the official Inertia documentation:
```
import { Head } from '@inertiajs/react'
<Head>
<title>Your page title</title>
<meta name="description" content="Your page description" />
</Head>
```
However, this code results in the following error:
`Type '{ children: Element[]; }' has no properties in common with type 'IntrinsicAttributes & InertiaHeadProps'.`
1. Install dependencies:[@types/react](https://www.npmjs.com/package/@types/react) and [@types/react-dom](https://www.npmjs.com/package/@types/react-dom)  (credit to …

Add children to InertiaHeadProps type

---

packages/react/src/usePage.ts
playgrounds/react/resources/js/Components/Layout.tsx

In #1396, the `usePage` generic type was (re)introduced for the React adapter.
When trying to use this, I've found it to be quite inconvenient because it's expecting us to pass in an entire `Page` type, which has things like the `url`, `component`, etc. with the props being nested under a `props` key.
This PR aims to solve that by changing the generic type to just accept the `PageProps` type.
This would also make the usage consistent with the Vue version.

Improve React `usePage` generic type

---

packages/vue2/src/useForm.ts
packages/vue3/src/useForm.ts

Right now there is no easy way to reinitialize a form using the form helper without providing all the data a second time. This creates unnecessary boilerplate in situations where a simple `form.reset()` isn't enough because you want to update the values based on props that may have changed. For example:
**Before (option 1):**
```js
// MyDialog.vue
const props = defineProps({
company_id: Number,
})
const open = ref(false)
const form = useForm({
first_name: '',
last_name: '',
email: '',
role: 'User',
company_id: props.company_id,
})
function open() {
form.first_name = ''
form.last_name = ''
form.email = ''
form.role = 'User'
form.company_id = props.company_id
open.value = true
}
```
**Before (option 2):**
```js
// MyDialog.vue
const props = defineProps({
company_id: Number,
})
const open = …
```

Add initialization callback to form helper in Vue adapters

---

packages/react/src/Link.ts

Right now the Inertia Link component doesn't have a displayName set, this doesn't cause any functional issues, but the displayName is often used by devtools to help make things a bit nicer.
The most recent example I've found of this causing issues is in Storybook - 
https://github.com/storybookjs/storybook/issues/20920#issuecomment-1499679321
If I use e.g. the Inertia Link component then it's showing as `<[Object object] href="/">This is a link</[Object object]>`.
While it could be argued that this is a storybook issue, other devtools also use displayName so it's an easy win for Inertia with no downsides.
We merged #351 for similar reasons.

Add `displayName` to `Link` component in React adapter

---

packages/core/src/types.ts
packages/core/tsconfig.json
packages/vue3/src/app.ts
playgrounds/vue3/resources/js/Components/Layout.vue

Hi,
Thanks for your great work on this package.
This PR fixes the lack of reactivity of `usePage` function return in Vue3 adapter.
Indeed, by returning `page.value`, we're losing the link with the page ref. 
When the page value is fully replaced, the props don't change in the component.
You can find a full simplified example [here](https://codesandbox.io/p/sandbox/nameless-http-78bf43?selection=%5B%7B%22endColumn%22%3A12%2C%22endLineNumber%22%3A16%2C%22startColumn%22%3A12%2C%22startLineNumber%22%3A16%7D%5D&file=%2Fsrc%2Fcomponents%2FNew.vue) with a comparison before/after.
References: 
- Discussion https://github.com/inertiajs/inertia/pull/1373#issuecomment-1400488273,
- Fix #1432
- [Another demo of the issue](https://stackblitz.com/edit/vue-n9k9av?file=src/App.vue)
- Transform the page …

Fix `usePage()` reactivity in Vue 3 adapter

---

package-lock.json
packages/vue2/package.json
packages/vue2/src/app.ts
playgrounds/vue2/resources/js/Components/Layout.vue

Right now the `usePage()` hook in the Vue 2 adapter isn't actually reactive. The following doesn't work:
```html
<script setup>
import { usePage } from '@inertiajs/vue2'
import { computed } from 'vue'
const page = usePage()
const appName = computed(() => page.props.appName)
</script>
```
This PR updates the Vue 2 adapter to use the same technique used in the Vue 3 adapter to solve this (see #1469).
The only issue here is that this requires Vue 2.7 features to fix this — the `computed()` and `reactive()` methods. Meaning anyone who is still using Vue 2.6 will need to also upgrade to Vue 2.7 when updating to the next release of Inertia. Given that this is the only way to solve this problem, I think that's a reasonable tradeoff.

Fix `usePage()` reactivity in Vue 2 adapter

---

packages/vue2/src/useForm.ts

This PR updates the form helper in the Vue 2 adapter to use the `reactive` and `watch` functions that are available in Vue 2.7. This is nicer than using `Vue.observable()` and the horrible technique I was previously using to create a watcher, and brings things inline with how they're implemented in the [Vue 3 form helper](https://github.com/inertiajs/inertia/blob/master/packages/vue3/src/useForm.ts).

Simplify the Vue 2 form helper

---

packages/vue3/src/app.ts

follow-up fix for #1469, as proposed by @reinink 
I have tested this with a local build and all is working as expected again.

Fix `usePage()` null object error in Vue 3 adapter

---

packages/vue3/src/useRemember.ts

Calling `useRemember` with a new object was being passed to `remembered` as a bare object, and therefore not a valid source for the Vue `watch` function. This converts it to either a ref or reactive as appropriate.
Fixes #1483

Save data to remembered as a valid watch source

---

packages/svelte/package.json
packages/svelte/src/useForm.js

This fixes two issues in useForm helper that I found.
- Form fields with objects as values (arrays/objects) has broken reactivity. This is because input `data` is shallow copied to `defaults`. Updating nested objects in form updates `defaults` object as well. Since the current form data is compared to `defaults`, no changes are detected.
- Broken `setStore`. Svelte's stores replaces store value with anything it receives from `update`'s callback function. In this case `setStore` creates completely new object instance every time it's called by returning `Object.assign({}, store, ...)`. Later when form submit fails, `this.clearErrors().setError(errors)` is called on object instance that request was made from which is NOT the object currently stored in form store hence nothing is cleared. …

fixes for svelte's useForm helper

---

packages/react/src/useForm.ts
packages/vue2/src/useForm.ts
packages/vue3/src/useForm.ts

Allows types than strings, based on the type passed in by the implementer.
fixes #1502 
Successfully tested locally in my project.

Fix form helper types for `setDefaults()` method (React) and `defaults()` method (Vue)

---

.github/workflows/build.yml

This PR adds playground builds to the CI process to ensure no easily caught regressions.

Build playgrounds in CI

---

packages/react/src/useForm.ts
packages/vue2/src/useForm.ts
packages/vue3/src/useForm.ts

A differing attempt to fix #1624. Tested Vue2, Vue3 and React in the included playgrounds, worked fine (after setting the language to TS in the tested Vue2 page). `FormDataType` exists so if someone wants to make a more restrictive type, it's easier for refactors.

Update `useForm` to accept interfaces

---

packages/react/src/Link.ts

An `onClick` in React — or event in the browser — never receives keyboard events. Even for a button that is “clicked” using enter or spacebar the browser creates a corresponding pointer event for the action that is passed into `onClick`.

Fix type of `onClick` for Link component in React

---

CHANGELOG.md
packages/vue2/src/link.ts
packages/vue3/src/link.ts

Same fix as #1699, except for Vue.
An `onClick` in Vue — or event in the browser — never receives keyboard events. Even for a button that is “clicked” using enter or spacebar the browser creates a corresponding pointer event for the action that is passed into `onClick`.

Fix type of `onClick` for Link component in Vue

---

CHANGELOG.md
packages/react/src/useForm.ts
packages/svelte/src/useForm.js
packages/vue2/src/useForm.ts
packages/vue2/tests/cypress/integration/form-helper.test.js
packages/vue2/tests/cypress/integration/remember.test.js
packages/vue3/src/useForm.ts

Right now when using the form helper, calling `form.reset()` does not clear the form errors. This feels like a bug, since if you're resetting the form to its initial state you likely also want the errors to be cleared out.
This PR updates the form helper to clear form errors when resetting the form:
```js
// will reset all form errors
form.reset()
```
If you're only resetting certain fields, only those corresponding errors will be cleared:
```js
// will only reset "name" and "email" errors
form.reset('name', 'email')
```

Clear errors on form reset

---

packages/react/src/Link.ts

this fixes #1511 
it's a more explicit version of @Gregory-Gerard recommended solution

Fix `Link` type in React

---

CHANGELOG.md
packages/react/src/useForm.ts
packages/svelte/src/useForm.js
packages/vue2/src/useForm.ts
packages/vue2/tests/cypress/integration/form-helper.test.js
packages/vue2/tests/cypress/integration/remember.test.js
packages/vue3/src/useForm.ts

This PR reverts #1568 due to the common use of `form.reset()` to clear password fields after failing to register or login where validation errors need to be preserved. We will need to rethink our approach to that PR.
Fixes https://github.com/laravel/jetstream/issues/1393

Revert "Clear errors on form reset (#1568)"

---

packages/svelte/src/Render.svelte

Fix #1733 
Fix #1621
When routing between layouts, Svelte ([v4.1.0 and above](https://github.com/inertiajs/inertia/issues/1621#issuecomment-1775805874)) will not slot in the pages correctly. 
This PR implements additional logic with a key block to guarantee accurate page rendering while maintaining the persistent layouts feature.
- I found a PR that includes this fix: https://github.com/inertiajs/inertia/pull/1705
- This issue may be related: https://github.com/inertiajs/inertia/issues/1670

Fix Svelte 4 slot rendering issues

---

packages/svelte/src/Link.svelte

Resolves #1627
Resolves #1635
Resolves #1835
Right now the Svelte adapter is throwing an ARIA warning during build:
```
Link.svelte:27:0 A11y: <svelte:element> with click, dblclick, mousedown, mousemove, mouseout, mouseover, mouseup handlers must have an ARIA role
```
While a couple possible solutions have been shared (#1635, #1835), I am pretty sure that this is actually a false positive and a good use case for a `svelte-ignore` comment, so that's what I've implemented here.

Fix accessibility warning in Svelte `Link` component

---

packages/core/src/router.ts
packages/core/src/types.ts
packages/react/src/Link.ts
packages/svelte/src/Link.svelte
packages/vue2/src/link.ts
packages/vue2/tests/app/Pages/Links/PartialReloads.vue
packages/vue2/tests/app/Pages/Visits/PartialReloads.vue
packages/vue2/tests/app/helpers.js
packages/vue2/tests/cypress/integration/links.test.js
packages/vue2/tests/cypress/integration/manual-visits.test.js
packages/vue3/src/link.ts

See https://github.com/inertiajs/inertia-laravel/pull/622

[1.x] Exclude properties from partial responses

---

packages/core/src/router.ts

Deep merge props on partial visits instead of simple concatenation, to preserve deeply nested props that are not present in the partial response. Array values will be replaced with new values.
Introduces required changes for https://github.com/inertiajs/inertia-laravel/pull/620
Initial response:
```json
{
"user": {
"id": 1,
"name": "New user",
"email": "boris@example.com"
}
}
```
Partial request:
```js
router.put(
'/profile',
{
name: 'Boris Lepikhin'
},
{
only: ['user.name'],
}
)
```
Page props (`auth.user.id` preserved):
```json
{
"user": {
"id": 1,
"name": "New user",
"email": "boris@example.com"
}
}
```

[1.x] Deep merge properties

---

CHANGELOG.md
packages/core/src/router.ts
packages/core/src/types.ts

Right now the `PreserveStateOption` type (used for the `preserveScroll` and `preserveState` options) accepts a generic string — however the only string value that's supported is `'errors'`, so I've tightened up this type to reflect that.
I've also updated the return type for `resolvePreserveOption`, which should only ever return a boolean.

Fix `preserveScroll` and `preserveState` types

---

CHANGELOG.md
packages/core/src/router.ts

Resolves #1885
Resolves #1883
This PR reverts the changes in #1877, which added deep merging of properties on partial reloads. Unfortunately this has some issues, specifically in situations where props that are objects have keys removed during a partial reload.

Revert "deep merge properties (#1877)"

---

packages/react/src/useForm.ts

Simple fix for a wrong type for the transform function in the react package.

[React] Fix wrong type in transform

---

packages/react/src/useForm.ts

This is a proposal for changing the ergonomics of the key-value variant for the `setData` hook in React.
Using this simple form as an example:
```ts
const form = useForm({
name: 'Alice',
lastname: 'Doe',
})
```
It is expected that sequential calls to `setData` will update the form data accordingly. However, subsequent calls overwrite the changes made by the previous calls.
```ts
form.setData('name', 'Bob') // { name: 'Bob', lastname: 'Doe'}
form.setData('lastname', 'Smith') // { name: 'Alice', lastname: 'Smith'}
```
Sequential `setData` calls use an updater function to batch the changes from multiple calls.
```ts
form.setData('name', 'Bob') // { name: 'Bob', lastname: 'Doe'}
form.setData('lastname', 'Smith') // { name: 'Bob', lastname: 'Smith'}
```
---
This can be achieved using [updater …

[React] Use updater function in `setData` in `useForm` hook

---

packages/core/src/shouldIntercept.ts

Fixes #1772 #1329 #1679
All major browsers except Safari trigger the `auxclick` instead of `click` when the middle button is clicked on a mouse. WebKit has a [long-standing bug](https://bugs.webkit.org/show_bug.cgi?id=22382) that does not adhere to this behavior, so Safari dispatches a plain old `click` event instead. But alas, we can key off of the [`button` property on `MouseEvent`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button#value) to detect if this is an auxiliary click, and skip intercepting in that case.
I had to tweak the TypeScript types here to handle receiving a `MouseEvent` and discriminate accordingly.

Skip intercepting non-left button clicks on links

---

packages/core/src/shouldIntercept.ts
packages/react/src/Link.ts

Thanks to some crafty sleuthing by @shengslogar (https://github.com/inertiajs/inertia/pull/1908#issuecomment-2190390026), there are a few things to clean up after #1908:
- The event we were passing to `shouldIntercept` from the React adapter was the React synthetic event, which does not have all the properties of the underlying native event. It seems wise to keep the intercept helper function framework-agnostic, so this change now passes the `event.nativeEvent` to `shouldIntercept`.
- The `event.which` property is [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/which). The purpose it previously served for evaluating `MouseEvent` eligibility is now covered by the newly-introduced `event.button` check.
- I realized TypeScript didn't have my back here to catch the type …

Fix types and remove use of deprecated browser event prop

---

CHANGELOG.md
packages/svelte/src/lib/components/Render.svelte

This PR fixes the `<Render />` component by checking for children components before attempting to pass the default slot to the rendered component.
Closes #1785.

[1.x] Fix 'received an unexpected slot "default"' warning

---

packages/core/src/router.ts

Hello!
We are having the following problem in our application.
We are using `<React.StrictMode>` in the application, this causes the application to redirect twice in dev mode.
This forces us to double the previous hash during development because it calls the same router logic twice.
For example it makes `exanple.com/#hi` become `exanple.com/#hi#hi` after the update
This fix would prevent that from happening. If so, would you have handled this differently? 
Thank you very much for Inertia! It's a cool project 😉

[1.x] Fix doubling hash in React StrictMode

---

packages/vue3/src/types.ts

This PR changes Vue 3 type augmentation to be placed in `vue` module instead of `@vue/runtime-core` [as it supposed to be](https://vuejs.org/guide/typescript/options-api.html#augmenting-global-properties).
Many infrastructure packages like [Vue Router](/vuejs/router/pull/2295), [Vue i18n](/intlify/vue-i18n/pull/1919) and [Nuxt](/nuxt/nuxt/pull/28542) already did so.

[1.x] Fix type augmentation for Vue 3

---

CHANGELOG.md
packages/core/src/router.ts
packages/vue3/src/useForm.ts
packages/vue3/src/useRemember.ts

This bug has been around for a while in Inertia.js _(see timeline below)_, and after digging into it with @jamesst20's help, we figured out the core issue: Inertia is trying to serialize proxy objects when it saves data to the history state. You might run into this using `useForm` _(fixed in 2021)_, `router.remember`, or even just scrolling, as Inertia saves scroll positions in history.
[`history.replaceState`](https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState#datacloneerror) uses `structuredClone`, which throws [`DataCloneError`](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone#datacloneerror) if it hits anything non-serializable.
To fix it, I’m using `JSON.parse(JSON.stringify())`. This is great for simple data structures, and it automatically strips …

[1.x] Fix "DataCloneError: <Object> could not be cloned"

---

packages/react/src/useForm.ts

When using the `useForm()` in a React component that has some heavy pure components(components using `React.memo`) as children and passing some methods returned by `useForm()` like `setData`, `clearErrors`, etc to them, on every re-render, these methods returned by `useForm()` are getting **new references** so new props are passed to these `React.memo()`ed children and they will be re-rendered unnecessarily. 
This pull request fixes this issue by using `useCallback` for those methods in the `useForm` hook.

[1.x] Fix useForm re-renders by memoizing functions in React

---

packages/vue2/src/useForm.ts
packages/vue3/src/useForm.ts

**reset** from **useForm** is not functional after a successful submission. This is due to the form's internal onSuccess hook setting defaults to the current form state (line 172).
**The bug happens in any version above 1.0.14 in vue3**
Look at **line  (172).**
https://github.com/inertiajs/inertia/blob/0fc4b1c8b91639ed58b44fafe8833f2108496de6/packages/vue3/src/useForm.ts#L163-L175
Whem we look at the source code of React and Svelte drivers, we dont see this behaviour. Older versions of the Vue codebase also do not have this line of code.
```javascript
import { useForm } from '@inertiajs/vue3'
const form = useForm({ email: '' })
```
```javascript
form.email = 'test@example.com'
```
```javascript
form.post("/endpoint", {
onSuccess: () => {
//after some secconds, make reset
setTimeout(() => …
```

[1.x] useForm wrongly overwrites default values ​​after successful submission

---

packages/vue2/src/useForm.ts
packages/vue3/src/useForm.ts

When calling `defaults()` on a form, the `isDirty` state does not reset as expected. This occurs because the watcher only monitors changes to the `form` reactive properties, while the `defaults()` method modifies the default properties, which are not part of the watched `form`. As a result, `isDirty` is never recalculated and remains `true`.
This fix ensures that `isDirty` accurately reflects the form's state after resetting to defaults similarly to how the React adapter does it.
Fixes #1862.

[1.x] Fix isDirty after form.defaults() call in Vue

---

packages/core/src/router.ts

When using `router.on()` it is always executed, this means the following won't work during SSR:
```html
<script setup>
import { router } from '@inertiajs/vue3'
router.on('start', (event) => {
console.log(`Starting a visit to ${event.detail.visit.url}`)
})
</script>
```
Instead, we'd need to wrap this in a `onMounted` hook, or check if the document/window exists;
```html
<script setup>
import { router } from '@inertiajs/vue3'
import { onMounted } from 'vue'
onMounted(() => {
router.on('start', (event) => {
console.log(`Starting a visit to ${event.detail.visit.url}`)
})
})
</script>
```
But since `router.on()` is already just a wrapper for `document.addEventListener()` I'd expect the wrapper to take care of that for you.
A simple fix I've made here is to simply check if we're in ssr with …

[1.x] Return early when using `router.on()` during SSR

---

.gitattributes

I realized the project is being classified as php based, but I think it would be more acurate to say it is based on javascript?
This is useful when people search for projects by language, if I'm looking for a javascript project on github, it would right now be excluded from search results, as it is being tagged as mainly php based.

[1.x] Update .gitattributes to exclude playgrounds/ from linguist inference

---

packages/core/src/router.ts

On Chrome iOS, calling `this.storeScrollPositions` (which uses `history.replaceState`) right before `this.setPage` in the router `visit` method caused timing issues with `history.pushState`, leading to navigation problems.
Wrapping `window.history.pushState` with `setTimeout` inside `router.pushState` fixes the issue. Using `setTimeout` defers `history.pushState` to the next event loop tick, preventing conflicts between `history.replaceState` and `history.pushState`. This change doesn’t introduce any side effects since `setTimeout` with a delay of 0 just delays the execution without altering functionality.
Fixes #1954.
https://github.com/user-attachments/assets/f7ad94e9-46fb-4bec-9897-8d54758cd951
https://github.com/user-attachments/assets/2bb29406-ceb8-41ef-b4bd-8a5bff2f75f0
We could …

[1.x] Fix history navigation issue on Chrome iOS

---

CHANGELOG.md
packages/core/src/router.ts

I noticed an issue introduced by #1984 when using the Vue 2/3 and Svelte adapters. On the playgrounds for these adapters, navigating through **Home** → **Users** → **Article** → **Form** and then trying to go back in history skips the **Article** page. 
After investigating, I found that `router.replaceState` (which remembers the form state) was being called **before** `router.pushState`, effectively replacing the **Article** history state.
I tried several approaches but determined that the safest solution is to scope the fix from #1984 specifically to Chrome on iOS, where the initial issue occurs. This avoids any unintended side effects in other browsers.
----
I’ve tested the fix across all adapters on **Chrome/Safari/Firefox** on macOS and **Chrome/Safari** on iOS, and everything is …

[1.x] Fix history navigation issue

---

CHANGELOG.md
packages/svelte/src/createInertiaApp.ts

[Sam reported](https://x.com/saml_dev/status/1843828546051158381) that the new svelte adapter adds ~500 kb to his app bundle size.
After some investigation I found the culprit, it’s the way we import the `VERSION` constant from the Svelte compiler in the `createInertiaApp.ts`. This PR fixes that.

Fix Svelte version import

---

CHANGELOG.md
packages/svelte/src/link.ts

Commit 69292ef already took care of the type issue reported in #2001. While looking into the type error, I noticed the custom events needed some adjustment for better type safety.
I also realized the action wasn’t supporting the new Svelte 5 event listener syntax (`onbefore`), so I’ve added support for both `on:before` and `onstart` (and all other events) in this PR.
----
Closes #2001

Fix `use:inertia` action event listeners types

---

packages/react/src/Link.ts

Right now, `onClick` handlers passed to the React `<Link />` component are only called when the prefetch mode is `click` as reported in #2018. This is PR fixes that.
Closes #2018.

[2.x] Fix `onClick` in React adapter

---

packages/core/src/response.ts

This was an accidental breaking change in 2.x, previously `$page.url` did not include the full URL, now it does. This PR fixes that.
Fixes #2020

[2.x] $page url should not include the host

---

packages/svelte/test-app/svelte.config.js

This PR reduces noise when running Playwright tests _(see below)_ to make it easier for us to spot errors when they happen.

[2.x] Suppress Svelte accessibility warnings from Playwright logs

---

packages/svelte/test-app/tsconfig.json
playgrounds/svelte4/resources/js/app.ts
playgrounds/svelte4/resources/js/ssr.ts
playgrounds/svelte4/tsconfig.json
playgrounds/svelte5/resources/js/app.ts
playgrounds/svelte5/resources/js/ssr.ts
playgrounds/svelte5/tsconfig.json

This PR fixes TypeScript module resolution issues within our monorepo setup that were preventing the detection of type errors during the launch of **v1.3.0-beta.1**. This happened because the `packages/svelte/test-app` and Svelte `playgrounds` projects weren't detecting type definitions from the Svelte adapter. The existing module resolution settings, copied from a fresh SvelteKit installation, were incompatible with our NPM workspace structure.
Changing the TypeScript module resolution to the same values as the other adapters fixes this issue in the Svelte adapter.

[2.x] Change TypeScript module resolution in the Svelte adapter

---

packages/core/src/encryption.ts
packages/react/test-app/Pages/History/Page.jsx
packages/svelte/test-app/Pages/History/Page.svelte
packages/vue3/test-app/Pages/History/Page.vue
tests/app/server.js
tests/history.spec.ts

Fixes the buffer size to account for multi-byte characters when encrypting history.
Fixes #2028

[2.x] Fix multi byte strings in history encryption + test

---

packages/core/src/eventHandler.ts
packages/core/src/page.ts
packages/core/src/router.ts
packages/core/src/types.ts
packages/vue3/test-app/Pages/DeferredProps/Page1.vue
tests/deferred-props.spec.ts

Currently, we only load deferred props on the `navigate` event, but when visiting the same page (e.g. clicking a link to the page you are currently on) that event doesn't get fired and the deferred props go back to their loading state and never load.
We now have a custom `loadDeferredProps` event that fires on every page swap, as it should.
Closes #2013.

[2.x] Fix loading deferred props when re-visiting the same page

---

packages/react/test-app/Pages/DeferredProps/Page1.jsx
packages/svelte/src/components/Deferred.svelte
packages/svelte/test-app/Pages/DeferredProps/Page1.svelte
packages/vue3/test-app/Pages/DeferredProps/Page1.vue
tests/app/server.js

In issue #2012, the `<Deferred />` component was rendering its default slot before the necessary props were updated, leading to errors when accessing properties on undefined objects. To address this, I updated the `<Deferred />` component to subscribe to the `$page` store and use `queueMicrotask` skip a beat and switch `loaded` when the props are expected to be updated.
#2036 improves how `$page` is updated making it more predictable. The approach in this PR resolves the reactivity issue in the `<Deferred />` component without modifying the `$page` store, maintaining compatibility for existing projects.

[2.x] Fix `<Deferred />` in Svelte adapter

---

packages/core/src/router.ts

The `prefetch` method needs to know about the current page, but there are scenarios where we may be calling this method prior to the page being set. 
This adjustment ensures the page is set before adding the prefetch to the request queue.
Fixes #2053

Ensure current page is set before prefetching

---

packages/core/src/history.ts
packages/core/src/page.ts

This PR addresses an issue where the component could technically be mounted before we set the new history state when history encryption is in use, causing `reload` to reload the incorrect URL (typically the previous URL).
Fixes #2093

Set the history state before swapping component

---

packages/react/test-app/Pages/WhenVisible.jsx
packages/svelte/test-app/Pages/WhenVisible.svelte
packages/vue3/src/whenVisible.ts
packages/vue3/test-app/Pages/WhenVisible.vue
tests/when-visible.spec.ts

This fixes an issue where the user doesn't pass anything in the default slot in Vue. We were previously just executing the function assuming a default slot existed, now we're testing for it before executing.
Fixes #2095

Ensure we have a default slot for WhenVisible before executing it

---

package-lock.json
packages/core/package.json
packages/core/src/progress-component.ts
packages/core/src/progress.ts
packages/core/src/types.ts

As mentioned in #2031, `nprogress` has been inactive for quite a long time and with the 2.x release it's probably smart to remove it as a dependency and bring it in house.
This also allowed for a refactor, bringing it up to more modern web standards. Among the improvements:
- Remove all vendor prefixes from css (all are now baseline)
- Use `classList` instead of manually parsing class attributes
- Use `style` property instead of manually parsing style attribute
It also allowed for tighter integration with the behavior we needed out of the component. Wins all around!
Fixes #2031

[2.x] Removal of NProgress dependency

---

packages/core/src/router.ts
tests/prefetch.spec.ts

Here's the scenario:
- User is on `/users`
- There is a `Link` to `/users` that prefetches on hover on the page
- If they hover that `Link` it will prefetch page and refresh the data on the current page
- If there is any changed form state, etc it gets reset back to its original state
My solution is: if we are trying to prefetch the current page, just don't. I can't think of a scenario where this is useful, we're already on the page, so we just abort it before it even kicks off.

Don't prefetch the current page

---

packages/core/src/router.ts
packages/core/src/types.ts
packages/react/test-app/Pages/ClientSideVisit/Page1.jsx
packages/react/test-app/Pages/ClientSideVisit/Page2.jsx
packages/svelte/test-app/Pages/ClientSideVisit/Page1.svelte
packages/svelte/test-app/Pages/ClientSideVisit/Page2.svelte
packages/vue3/test-app/Pages/ClientSideVisit/Page1.vue
packages/vue3/test-app/Pages/ClientSideVisit/Page2.vue
tests/app/server.js
tests/client-side-visits.spec.ts

This PR adds the ability to make client side visits via `router.push` and `router.replace`:
```ts
router.replace({
props: (props) => ({ ...props, foo: 'foo from client' }),
})
router.push({
url: '/my-page',
component: 'MyPage',
props: {
baz: 'baz from client',
},
})
```
The current page gets merged into the params, you are responsible for overriding anything from the current page that you want changed.

[2.x] Client side visits

---

packages/core/src/shouldIntercept.ts
packages/react/src/Link.ts

In #1910 (d53b2b3), we switched to passing `event.nativeEvent` to `shouldIntercept` in an attempt to consistently always pass native browser events to this framework-agnostic helper. This actually introduced a bug though, because `currentTarget` is _different_ on React's synthetic event vs. the underlying native event. The correct value for `currentTarget` lives on the synthetic event.
Since we are no longer relying on `event.which` (and this is the only property we used to be concerned with that was not included on the React synthetic event), we'll simply move back to passing the React synthetic event to `shouldIntercept`.

[1.x] Restore command + click behavior on Inertia links in React

---

.github/CONTRIBUTING.md

Hi, it seems like the contributing docs mention a non-existing command to start the SSR server.
I've replaced it with the ones mentioned in the Inertia [docs](https://inertiajs.com/server-side-rendering#running-the-ssr-server).

docs: fix incorrect SSR server start command

---

.github/workflows/build.yml

Hi, the current build action shows a warning for usage of the deprecated `actions/cache@v2`. This PR should fix that.

ci: fix cache deprecation warnings

---

package.json

This PR simply adds several helper scripts so we can run tests and build the test app from the root directory.

Add helper scripts for running tests

---

packages/core/src/response.ts

The previous method for stripping the origin from absolute page URLs produces malformed output when the `host` string happens to appear multiple times in the URL.
```js
// Old logic
"https://example.com/foo?return_to=https%3A%2F%example.com%2Fbar".split("example.com").pop() === "%2Fbar" 
// New logic
const url = new URL("https://example.com/foo?return_to=https%3A%2F%example.com%2Fbar")
url.pathname + url.search + url.hash === "/foo?return_to=https%3A%2F%example.com%2Fbar"
```
I had some trouble getting an automated test case to work in `response.test.ts` (they all seem to failing for me when I try to run `vitest` 🤔 ), but happy to take another crack at it with some guidance.

More resilient logic for stripping the origin from page URLs

---

packages/core/src/history.ts

Ensure callback execution regardless of `preserveUrl` in `history.pushState` and `history.replaceState` #2162

Ensure callback execution

---

packages/react/src/WhenVisible.ts
packages/react/test-app/Pages/WhenVisible.jsx
packages/svelte/test-app/Pages/WhenVisible.svelte
packages/vue3/test-app/Pages/WhenVisible.vue
tests/app/server.js
tests/when-visible.spec.ts

Closes #2152. Adds the needed dependencies to the useEffect and adds a few refs to keep the same fetching behavior as before.

 WhenVisible useEffect function is not recreated when params change. #2152 

---

packages/core/src/router.ts

Updates the `prefetch` method signature in `router.ts` to match the [documented](https://inertiajs.com/prefetching#programmatic-prefetching) behavior by providing a default value for the `cacheFor` option. This fixes TS errors when calling `router.prefetch` with two arguments and aligns with the documented API.
Calling `router.prefetch` to programmatically prefetch data like so:
```js
router.prefetch(route('customers.show', row.original.id), { method: 'get' })
```
Results in `TS2554: Expected 3 arguments, but got 2.` and `Uncaught TypeError: Cannot destructure property 'cacheFor' of 'undefined' as it is undefined.` on runtime. This a result of not having a default value on the `prefetch` method on the router.
```diff
- public prefetch(href: string | URL, options: VisitOptions = {}, { …
```

Fix prefetch missing cacheFor default value

---

packages/vue3/src/types.ts

Hello 👋,
Vue recommends to augment `vue` instead of its sub-dependencies so this PR removes the augmentation of `@vue/runtime-core` and augments `vue` instead.
- https://vuejs.org/guide/typescript/options-api.html#augmenting-global-properties
- https://github.com/nuxt/nuxt/pull/28542
- https://github.com/nuxt/nuxt/pull/18505
- https://github.com/inertiajs/inertia/pull/1958

refactor: augment `vue` instead of `@vue/runtime-core`

---

playgrounds/svelte4/composer.json
playgrounds/svelte4/composer.lock
playgrounds/svelte5/composer.json
playgrounds/svelte5/composer.lock
playgrounds/vue3/composer.json
playgrounds/vue3/composer.lock

The paths to the inertia-laravel dependency inside the svelte playgrounds are specified for a local setup which does not work if you don't clone the repos exactly the same way. I would suggest using the same version specified in the react playground, without local repositories.

Fix playground dependencies

---

packages/react/src/useForm.ts
packages/svelte/src/useForm.ts
packages/vue3/src/useForm.ts

The inclusion of `data` in `VisitOptions` can be misleading when using `useForm`. We should update the type definitions to exclude the `data` property in this context to prevent confusion.
Closes #2056.

[2.x] Remove `data` option from `useForm` options type

---

packages/core/src/eventHandler.ts
packages/core/src/history.ts
packages/core/src/page.ts
packages/vue3/test-app/Pages/History/Page.vue
tests/history.spec.ts

v2.0.1 introduced a bug where if you did the following sequence of events the URL wouldn't ultimately resolve to the correct final URL:
- Navigate to a another page
- Scroll down on that page
- Press the back button
This PR ensures that even when handling the pop state, our internal history object is updated with the current page. Thanks to @crynobone for the catch.

Fix for scroll + back bug

---

packages/core/src/history.ts
packages/react/test-app/Pages/Visits/ReloadOnMount.jsx
packages/svelte/test-app/Pages/Visits/ReloadOnMount.svelte
packages/vue3/test-app/Pages/Visits/ReloadOnMount.vue
tests/app/server.js
tests/manual-visits.spec.ts

This PR should fix an issue where we try to save the initial scroll state before we even have any history state.
Should fix https://github.com/inertiajs/inertia/issues/2195

Fix: Reload on mount

---

CHANGELOG.md
packages/core/src/initialVisit.ts

This PR fixes a bug where full page visits with anchor links (ie. `/page#someid`) don't work because the scroll restoration interferes with it.
The reason we do scroll restoration on initial page visits is to maintain the scroll position when reloading a page (see #1360). However, we don't want to do this when it's just a standard "navigate" type.
This PR adds a navigation type to see if it's a "reload" visit, and only then does scroll restoration.

Fix anchor links on initial visits

---

packages/core/src/history.ts

This fixes https://github.com/inertiajs/inertia/issues/2204 
We have experienced the same error from one of our apps, although it's still unclear exactly what's going on. I decided to push this PR because it may help people out there until someone smarter figures out the source of this.
To expand on what I know so far: client-side navigation is broken after performing a full page load through InertiaJS' 409 Conflict protocol ([a location visit](https://github.com/inertiajs/inertia/blob/37f9180faa17a86b714c9ce22f0a2f9866c8c47f/packages/core/src/response.ts#L79)). It doesn't occur for every route/component though. The error experienced is:
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'page')
```
The error points to:
```javascript
this.doReplaceState({
page: …
```

Fix history state errors

---

packages/react/src/Deferred.ts

This one just tripped me up for a bit
I passed in an object instead of a string for the `data` prop and the error wasn't descriptive enough to help me.
- ❌ Error before: '`<Deferred>` requires a `data` prop'
- ✅ Error now: '`<Deferred>` requires a `data` prop to be a string or array of strings'

Deferred: More descriptive Deferred data prop error

---

packages/core/src/initialVisit.ts
tests/links.spec.ts

When performing a location redirect and the user is returned to the Inertia application, the location handler tries to decrypt the history of the page, but at this point, the state hasn't been set yet, so it returns `undefined` when attempting to access the page state through `window.history.state?.page`, this scenario is further explained by the issue [#2262](https://github.com/inertiajs/inertia/issues/2262)
I'm not sure why the `decrypt` function is being called at this stage in the `InitialVisit.handle()` as the router is being initialized and the history state hasn't been set yet, so trying to decrypt the history state at this point will always return `undefined`.

Fix location return history decryption throwing error

---

playgrounds/react/resources/js/Components/TestGrid.tsx
playgrounds/react/resources/js/Components/TestGridItem.tsx
playgrounds/react/resources/js/Pages/Async.tsx
playgrounds/react/resources/js/Pages/Poll.tsx
playgrounds/svelte5/resources/js/Components/TestGrid.svelte
playgrounds/svelte5/resources/js/Components/TestGridItem.svelte
playgrounds/svelte5/resources/js/Pages/Async.svelte
playgrounds/svelte5/resources/js/Pages/Poll.svelte

Added Async and Poll Page to React and Svelte5 Playgrounds to properly test the new features

Added missing pages to React and Svelte5 playrounds

---

package-lock.json
packages/react/package.json
packages/react/src/useForm.ts
packages/react/tsconfig.json
packages/svelte/package.json
packages/svelte/src/useForm.ts
packages/vue3/package.json
packages/vue3/src/remember.ts
packages/vue3/src/useForm.ts
packages/vue3/src/useRemember.ts

This PR replaces `lodash.isequal` by `@gilbarbara/deep-equal` and `lodash.clonedeep` by `klona` to decrease the bundle size in ~6kB (gzip).

chore: replace lodash to decrease bundle size

---

packages/react/src/createInertiaApp.ts
packages/vue3/src/createInertiaApp.ts

This PR ports existing logic from svelte adapter to the react and vue adapter to allow graceful handling for non-inertia pages:
before:
```js
const rootId = 'app'
if (document.getElementById(rootId)) {
void createInertiaApp({
id: rootId,
//...
})
}
```
after:
```js
void createInertiaApp({
setup({ el, App, props }) {
if (el) {...}
}
})
```

Allow better missed root handling

---

packages/core/src/history.ts

If there was a change to the url that interia was not aware of, such as the modification of a query parameter, this would cause the current url to be overwritten and reset to a previous value.
Since passing the url is optional, we can simply not pass it to avoid overriding the url in any case.
Closes https://github.com/inertiajs/inertia/issues/2233

do not pass url when storing scroll state to history

---

package-lock.json
packages/core/package.json
packages/core/src/server.ts

Reattempt of #1909 for 2.x
Currently the Inertia SSR server would only run on a single thread, so on high load this might have implications, since the Node process could only take 100% on a single core/thread.
Node has the cluster module [nodejs.org/api/cluster.html](https://nodejs.org/api/cluster.html), which would make it possible to start multiple Node servers on the same port, then each request would be dealt with by each thread in a round-robin way.
With this PR it's possible to enable clustering by using;
```ts
createServer(
(page) => createInertiaApp( ... ),
{
cluster: true,
}
)
```
Massive thanks to @christianschoenmakers who discovered the issue and asked about it on the Inertia.js Discord server:
> Hi guys! I'm using Laravel Inertia + Vue with SSR. Sometimes the site is becoming …

[2.x] SSR clustering

---

packages/vue3/src/link.ts

The Link component has support for the href prop to be an object. However, Object type is missing from the allowed types for the href prop. Resulting in route objects not being allowed to be passed to the href prop.
For example, with wayfinder a controller action or route can not be passed directly to the href prop of Link:
```vue
<script setup lang="ts">
import { about } from "@/routes/about";
</script>
<template>
<div>
<Link :href="about()"> About </Link>
</div>
</template>
```
But this does not currently work as the only allowed type for href is String. The typescript definition allows the Object type so the IDE doesn't throw an error. The error is thrown in the browser:

Allow Object type for href prop

---

packages/react/src/useForm.ts

- Fixed build error when using `skipLibCheck: false` and `strict: true`
```
> tsc && vite build
node_modules/.pnpm/@inertiajs+react@2.0.7_react@19.1.0/node_modules/@inertiajs/react/types/useForm.d.ts:4:61 - error TS2344: Type 'TForm' does not satisfy the constraint 'Record<any, any>'.
4 type SetDataByKeyValuePair<TForm> = <K extends FormDataKeys<TForm>>(key: K, value: FormDataValues<TForm, K>) => void;
~~~~~
node_modules/.pnpm/@inertiajs+react@2.0.7_react@19.1.0/node_modules/@inertiajs/react/types/useForm.d.ts:4:28
4 type SetDataByKeyValuePair<TForm> = <K extends FormDataKeys<TForm>>(key: K, value: FormDataValues<TForm, K>) => void;
~~~~~
This type parameter might need an `extends Record<any, any>` constraint.
node_modules/.pnpm/@inertiajs+react@2.0.7_react@19.1.0/node_modules/@inertiajs/r …
```

fix: build error because of invalid type definitions

---

packages/core/src/router.ts
packages/core/src/types.ts

All credit to @7nohe from https://github.com/inertiajs/inertia/pull/1537
```ts
import { router } from '@inertiajs/vue3'
type RequestData = { message: string }
router.post<RequestData>(url, { title: 'hello' }, options) // <- TypeScript Error
router.post<RequestData>(url, { message: 'hello' }, options) // <- OK
```

Improve type checking of request data

---

packages/core/src/requestParams.ts
tests/links.spec.ts
tests/manual-visits.spec.ts

All credit to @edgars-vasiljevs in https://github.com/inertiajs/inertia/pull/1651
Previously, all Inertia GET requests had `Content-Type: application/json` header applied because empty object is passed as a payload. Axios sees an object and sets content type to `application/json` even though request body is empty.
This led to odd behavior on Laravel's side as the request was interpreted as JSON.
The payload now defaults to `null`, thereby removing the `Content-Type: application/json` header from the request.

Remove empty payload from GET requests

---

packages/core/src/url.ts

In versions prior to `v2.0.8`, `deepmerge` treated `undefined` values as a signal to remove keys from url search parameters.
So:
```js
router.reload({ data: { foo: undefined } });
```
would remove `?foo=...` from the URL entirely.
In [this commit](https://github.com/inertiajs/inertia/commit/2ed6671cd7288a8a0987a51a6f4bfc198241fc78), `deepmerge` was removed and replaced with an `es-toolkit` method of `merge` in [packages/core/src/url.ts](https://github.com/inertiajs/inertia/commit/2ed6671cd7288a8a0987a51a6f4bfc198241fc78#diff-5ccc166b9dbc7c5cb9816b15b8296bed6bc3363ff434a96da345e2e99d02779e). This new method **does not omit** `undefined` values and instead serializes them as empty strings.
So:
```js
{ foo: undefined } 
```
becomes
```js
?foo=
```
This is a subtle but breaking change in …

Corrects url search parameter merge logic to match behavior prior to v2.0.8

---

packages/core/src/eventHandler.ts
packages/react/test-app/Pages/History/Version.jsx
packages/svelte/test-app/Pages/History/Page.svelte
packages/svelte/test-app/Pages/History/Version.svelte
packages/vue3/test-app/Pages/History/Version.vue
tests/app/server.js
tests/history.spec.ts

This PR adds a check to the pop state listener that checks if the version hash in the history state is the current version hash, if it isn't, it will fetch the response fresh from the server.

On back button, fetch from server if version hash is not current

---

packages/core/src/url.ts

This PR slightly changes the host detection for URLs in order to properly support URLs that have a custom protocol.
**Why a custom protocol?**  ...you might ask.
Great question!
This will allow us to make use of Inertia within a NativePHP iOS application, where the internal URL protocol is `php://`.
With the current hardcoded check for `https?`, the URL generation ends up to become wrong when using a custom protocol.
As the regular expression still checks for the beginning of the string, I don't really see an issue with this.

Allow custom URL protocols

---

packages/core/src/page.ts
packages/core/src/router.ts
packages/react/src/App.ts

As reported in #2366 if we try to run make a request with router inside a useEffect() and the page is the first page loaded it will fail because router is not initialized yet because of how react executes the order of useEffects (bottom to top).
To fix it I splitted the router init, adding a setter for the swapComponent handler to set it inside an useEffect (mandatory).

Initialize router before components in React

---

packages/core/src/page.ts
packages/core/src/router.ts
packages/react/src/App.ts
packages/react/test-app/Pages/Visits/ReloadOnMount.jsx

This is a cleanup of PR #2379.
* `isRouterInitialized` has been renamed to `routerIsInitialized`.
* ~~The `routerIsInitialized` bool was enough to fix the problem. The additional `setSwapComponent` logic doesn't seem to provide any benefits. Perhaps this was needed before `currentIsInitialPage` [was introduced](https://github.com/inertiajs/inertia/pull/2377), but I can't reproduce it.~~
* The `setSwapComponent` has been removed to prevent introducing another public method on the core router. The swapping of the `swapComponent` method is now handled internally in `App.ts`. `swapComponent` is now simply a variable that gets replaced in the `useEffect` hook.
* There was already a test for this (*can reload on mount* in `manual-visits.spec.ts`) but in the React implementation it was using a …

Remove `setSwapComponent` method and cleanup after PR #2379

---

packages/react/src/Head.ts
packages/react/test-app/Pages/Head.jsx
packages/vue3/src/head.ts
packages/vue3/test-app/Pages/Head.vue
tests/head.spec.ts

This PR fixes #2362 by escaping the attribute values on tags that are passing into the `Head` component. Currently, passing this line of valid HTML will break:
```html
<meta name="description" content='This is the "best" example' />
```
The imported `escape` method is really small, but since we're already relying on `es-toolkit`, I think it's fine to leverage it. Still draft because it misses tests.

Escape the attribute values that are passed into the `Head` component

---

packages/react/src/Link.ts

Use `CacheForOption` type in React `Link` component

---

packages/core/src/eventHandler.ts
packages/react/test-app/Pages/Links/CancelSyncRequest.jsx
packages/svelte/test-app/Pages/Links/CancelSyncRequest.svelte
packages/vue3/test-app/Pages/Links/CancelSyncRequest.vue
tests/app/server.js
tests/links.spec.ts

This PR fixes a navigation issue that happened when a user went back in their browser history while a new page was still loading.
Previously, if a user navigated from `/page1` to `/page2`, then clicked a link to `/page3` (which is slow), and immediately pressed the browser's back button, `/page1` would appear but the request to `/page3` would still be running. Once finished, it would show `/page3`.
Now when a user goes back in history (while a new page is still loading), all pending (sync) requests are cancelled.

Cancel sync request on popstate event

---

packages/core/src/types.ts

Before today, I could write the following code:
```ts
router.replace({
url: `/some-url`,
preserveScroll: true,
preserveState: true,
})
```
However, with the latest release, now I receive a Typescript error:
> Argument of type '{ url: string; preserveScroll: true; preserveState: true; }' is not assignable to parameter of type 'ClientSideVisitOptions'.    │
│   Property 'errorBag' is missing in type '{ url: string; preserveScroll: true; preserveState: true; }' but required in type 'ClientSideVisitOptions'.
This pull request makes the `errorBag` property optional.

Make errorBag parameter optional

---

packages/core/src/router.ts
packages/core/src/types.ts

This builds on the recent change (#2304 & #1537) where `Visit` was made generic. Since `PendingVisit` is based on `Visit`, it made sense to make it generic too, along with related types like `VisitCallbacks`.
Now we can pass a data type to those hooks, which helps with type checking when working with things like `onBefore`, `onError`, etc.
Example:
```ts
const options: VisitHelperOptions<MyFormData> = {
onBefore: (visit: PendingVisit<MyFormData>) => {
// visit.data is now typed
},
onError: (errors) => {
// ...
},
};
```
This just makes things a bit smoother and safer when working with form data and Inertia events.

Add missing generic type support to PendingVisit and VisitHelperOptions

---

packages/core/src/router.ts
packages/core/src/types.ts
packages/core/src/url.ts
packages/react/src/Link.ts
packages/vue3/src/link.ts
tests/core/url.test.ts

This PR brings some improvements to the TypeScript implementation:
- The `Link` component now accepts a `FormData` type as `data`.
- The `href` attribute of the `Link` component is now optional as it already defaulted to `''` in the components.
- When making Client Side Visits, it expected the returned props to include an `errors` key. That's not required anymore.

TypeScript improvements for `Link` component and Client Side Visits

---

packages/react/src/Deferred.ts
packages/react/src/WhenVisible.ts

ReactNode includes all the possible renderable types. The current definitions misses some types, this will throw type error for example:
```
<Deferred data="options" fallback={<span>Fallback</span>}
<div>first line</div>
<div>second line</div>
</Deferred>
```

Use ReactNode type for children props

---

tests/links.spec.ts

This test was a bit flaky, failing sometimes on the first run.

Improve test that waits for scroll position restoration

---

packages/react/src/useForm.ts
packages/svelte/src/useForm.ts

Use `FormDataType` in the React and Svelte implementations as well.

Improve consistency in `useForm` across adapters

---

packages/svelte/src/components/Form.svelte
packages/svelte/src/useForm.ts

Fixes TS errors when accessing errors within the `<Form>` component

TS improvements to Svelte's `<Form>` and `useForm()` implementations

---

packages/core/src/types.ts
packages/react/src/Form.ts
packages/react/test-app/Pages/FormComponent/Ref.jsx
packages/svelte/src/components/Form.svelte
packages/svelte/test-app/Pages/FormComponent/Ref.svelte
packages/vue3/src/form.ts
packages/vue3/test-app/Pages/FormComponent/Ref.vue
tests/app/server.js
tests/form-component.spec.ts

This PR adds programmatic access to Form component methods and state via refs:
```vue
<script setup>
import { Form } from '@inertiajs/vue3'
import { ref } from 'vue'
const formRef = ref()
const submitForm = () => {
formRef.value.submit()
}
const checkState = () => {
console.log('Is dirty:', formRef.value.isDirty)
console.log('Has errors:', formRef.value.hasErrors)
console.log('Errors:', formRef.value.errors)
}
</script>
<template>
<Form ref="formRef" action="/submit" method="post">
<input name="email" type="email" />
<button type="submit">Submit</button>
</Form>
</template>
```

Add Form component ref support

---

packages/core/src/url.ts
packages/react/test-app/Pages/FormComponent/EmptyAction.tsx
packages/svelte/test-app/Pages/FormComponent/EmptyAction.svelte
packages/vue3/test-app/Pages/FormComponent/EmptyAction.vue
tests/app/server.js
tests/core/url.test.ts
tests/form-component.spec.ts

This PR fixes an issue where the`<Form>` component would not correctly submit the data to the current URL when it has more than one segment and when the `action` attribute is missing:
```
<Form method="post">
...
</Form>
```

Fix empty action in `<Form>` component when the current URL has more than one segment

---

packages/core/src/types.ts
packages/react/test-app/Pages/FormComponent/UppercaseMethod.tsx
packages/svelte/test-app/Pages/FormComponent/UppercaseMethod.svelte
packages/vue3/src/form.ts
packages/vue3/test-app/Pages/FormComponent/UppercaseMethod.vue
tests/app/server.js
tests/form-component.spec.ts

The `method` attribute of the classic HTML `<form>` element is case-insensitive. This PR brings support for that as well in the Inertia `<Form>` component.

Support uppercase method in `<Form>` component

---

packages/core/src/types.ts
packages/react/src/Form.ts
packages/react/test-app/Pages/FormComponent/AfterSubmit.tsx
packages/svelte/src/components/Form.svelte
packages/svelte/test-app/Pages/FormComponent/AfterSubmit.svelte
packages/vue3/src/form.ts
packages/vue3/test-app/Pages/FormComponent/AfterSubmit.vue
tests/app/server.js
tests/form-component.spec.ts

This PR adds an `afterSubmit` prop to the `Form` component, allowing you to `reset`, `resetAndClearErrors`, and/or `clearErrors` after a form submission.
```tsx
<Form method="post" afterSubmit={(props) => props.reset('name')}>
<input type="text" name="name" id="name" placeholder="Name" defaultValue="John Doe" />
<input type="email" name="email" id="email" placeholder="Email" defaultValue="john@doe.biz" />
<button type="submit">Submit</button>
</Form>
```
This is fired right after the `onFinish` event in the request lifecycle.
I also updated the `Form` component `reset` function to receive field names in the event that the user wants to reset individual fields instead of the whole form.
Questions:
- Do we like `afterSubmit`?
- Is the timing right in the request lifecycle (after …

Add `onSubmitComplete` prop to `Form` component

---

packages/core/src/resetFormFields.ts
packages/react/test-app/Pages/FormComponent/SubmitComplete/Redirect.tsx
packages/svelte/test-app/Pages/FormComponent/SubmitComplete/Redirect.svelte
packages/vue3/test-app/Pages/FormComponent/SubmitComplete/Redirect.vue
tests/app/server.js
tests/form-component.spec.ts

If the response to a form submission using the `Form` component is a redirect, any call to `reset` would fail because the form element is no longer on the page. This PR adds a check for the form element before continuing with the reset.

Fix for manipulating form after redirect in `onSubmitComplete`

---

packages/core/package.json
packages/core/src/formObject.ts
packages/core/src/prefetched.ts
packages/react/package.json
packages/react/src/Form.ts
packages/react/src/Head.ts
packages/react/src/useForm.ts
packages/svelte/package.json
packages/svelte/src/components/Form.svelte
packages/svelte/src/useForm.ts
packages/vue3/package.json
packages/vue3/src/form.ts
packages/vue3/src/head.ts
packages/vue3/src/remember.ts
packages/vue3/src/useForm.ts
packages/vue3/src/useRemember.ts
pnpm-lock.yaml

This is quite an unusual PR, but it reverts #2210. Inertia's build config currently targets ES2020, but `es-toolkit` targets ESNext. I've investigated some alternatives:
- Bundle the used `es-toolkit` functions by putting them in the `allowList` of `nodeExternalsPlugin()`. This increases the build-size by 18-55%, which is unacceptable. Of course, no tree-shaking here.
- Copy the used functions into the project itself. I honestly don't want the maintenance burden of this, and again, no tree-shaking.
- Bump the Inertia target to ESNext. Honestly not a bad idea, but definitely a breaking change if we do this in a minor or patch release. So, something we should probably do for Inertia 3.
Fixes #2458.

Revert to back to Lodash to retain ES2020 compatibility

---

packages/react/src/Form.ts
packages/react/test-app/Pages/FormComponent/ChildComponent.tsx
tests/app/server.js
tests/form-component.spec.ts

This defers updating the `isDirty` state until after DOM changes are complete. Since we base the dirty state on the DOM using `new FormData(formElement)`, we need to ensure child components have finished updating their `value` attributes before we check the form state.
The fix wraps `setIsDirty` in `startTransition()` within `updateDirtyState` to defer the state update until after the current render cycle.

Update dirty state after DOM changes (React only)

---

packages/react/src/useForm.ts
packages/react/test-app/Pages/FormHelper/EffectCount.tsx
tests/app/server.js
tests/form-helper.spec.ts

In Laravel Cloud's edit dialogs, we have effects that watch for changes to the model we're passing in, then set the form data to that model's properties and sets the defaults.
Previously, we had to leave `setDefaults` out of the effect's dependency array and ignore the ESLint error because `setDefaults`'s memoization was dependent on the `data` property, so it would cause an infinite loop:
```
useEffect(() => {
setData(model);
setDefaults();
}, [model, setData]); // eslint-disable-line react-hooks/exhaustive-deps
```
The correct way would be to include the `setDefaults` function as a dependency:
```
useEffect(() => {
setData(model);
setDefaults();
}, [model, setData, setDefaults]);
```
This PR uses Kent C. Dodd's "latest ref" pattern to remove `data` from the dependency array. [This is an …

Remove data from the dependency array of setDefaults

---

release.sh
tests/form-component.spec.ts
tests/form-helper.spec.ts
tests/head.spec.ts
tests/links.spec.ts
tests/manual-visits.spec.ts
tests/prefetch.spec.ts
tests/support.ts

This PR is a little round of cleanup and improving tests that turn out to be flaky in CI. There's still a *scroll restoration* test that sometimes fails, but I'm not sure if that's a flaky test or if the actual implementation should be improved.

Fix flaky tests in CI

---

package.json
playwright.config.ts
pnpm-lock.yaml
tests/events.spec.ts
tests/form-component.spec.ts
tests/form-helper.spec.ts
tests/svelte.spec.ts

We previously pinned Playwright to `<1.53.0` because newer versions removed the `DeferRendererTasksAfterInput` feature from the `--disable-features` launch option, which caused several tests to fail.
This PR fixes those tests and bumps Playwright to the latest version.

Bump Playwright

---

packages/core/src/history.ts
packages/core/src/initialVisit.ts
tests/remember.spec.ts

This PR fixes an issue where Inertia restores the remembered state after a browser refresh. This should only happen when using the back/forward browser buttons.

Don't restore remembered state after a refresh

---

packages/core/src/infiniteScroll/data.ts
packages/core/src/infiniteScroll/elements.ts
packages/core/src/types.ts
packages/react/src/InfiniteScroll.ts
packages/react/test-app/Pages/InfiniteScroll/RememberState.tsx
packages/svelte/src/InfiniteScroll.svelte
packages/svelte/test-app/Pages/InfiniteScroll/RememberState.svelte
packages/vue3/src/infiniteScroll.ts
packages/vue3/test-app/Pages/InfiniteScroll/RememberState.vue
tests/app/server.js
tests/infinite-scroll.spec.ts

This PR fixes an issue where the `<InfiniteScroll>` component's state would not be remembered correctly when navigating away to another page, and coming back to it with the browser's *back button*.

Remember Infinite Scroll state

---

packages/core/src/response.ts
packages/react/test-app/Pages/InfiniteScroll/DualContainers.tsx
packages/svelte/test-app/Pages/InfiniteScroll/DualContainers.svelte
packages/vue3/test-app/Pages/InfiniteScroll/DualContainers.vue
tests/app/eloquent.js
tests/app/server.js
tests/infinite-scroll.spec.ts

The PR makes sure the `ScrollProp` metadata is preserved on pages with `<InfiniteScroll>` components when making Partial Reloads.

Preserve `ScrollProp` on Partial Reloads

---

packages/core/src/eventHandler.ts
packages/core/src/scroll.ts
packages/react/test-app/Layouts/WithScrollRegion.tsx
packages/react/test-app/Layouts/WithoutScrollRegion.tsx
packages/react/test-app/Pages/Links/UrlFragments.tsx
packages/react/test-app/Pages/Visits/UrlFragments.tsx
packages/svelte/test-app/Layouts/WithScrollRegion.svelte
packages/svelte/test-app/Layouts/WithoutScrollRegion.svelte
packages/svelte/test-app/Pages/Links/UrlFragments.svelte
packages/svelte/test-app/Pages/Visits/UrlFragments.svelte
packages/vue3/test-app/Layouts/WithScrollRegion.vue
packages/vue3/test-app/Layouts/WithoutScrollRegion.vue
packages/vue3/test-app/Pages/Links/UrlFragments.vue
packages/vue3/test-app/Pages/Visits/UrlFragments.vue
tests/links.spec.ts
tests/manual-visits.spec.ts

This PR fixes the flakiness we've been seeing when testing the React adapter in CI. There was a timing issue where the scroll positions were restored quicker than the test page had registered the scroll listener.
In the core adapter, the `window.requestAnimationFrame` wrapping has been moved from `eventHandler.ts` to `scroll.ts`. This ensures that the scroll restoration always runs in that callback.

Improve testing of scroll restoration

---

packages/core/src/infiniteScroll.ts
packages/core/src/infiniteScroll/data.ts
packages/core/src/infiniteScroll/elements.ts
packages/core/src/infiniteScroll/queryString.ts
packages/core/src/types.ts
packages/react/src/InfiniteScroll.ts
packages/react/test-app/Pages/InfiniteScroll/InfiniteScrollWithLink.tsx
packages/react/test-app/Pages/InfiniteScroll/Links.tsx
packages/svelte/src/InfiniteScroll.svelte
packages/svelte/test-app/Pages/InfiniteScroll/InfiniteScrollWithLink.svelte
packages/svelte/test-app/Pages/InfiniteScroll/Links.svelte
packages/vue3/src/infiniteScroll.ts
packages/vue3/test-app/Pages/InfiniteScroll/InfiniteScrollWithLink.vue
packages/vue3/test-app/Pages/InfiniteScroll/Links.vue
tests/app/server.js
tests/infinite-scroll.spec.ts

This PR improves the cleanup of registered event listeners when navigating away from pages with one or more `<InfiniteScroll>` components:
* The `IntersectionObserver` listeners (for URL synchronization) got already disconnected when navigating away, but the callback is debounced so that it would still execute. That has been fixed.
* The Inertia `success` callback that checks if a `ScrollProp` should be reset now checks if the event is for the same component, otherwise it ignores it.
* Added tests for the changes above and also for prefetching pages with `<InfiniteScroll>` components.

Improve `<InfiniteScroll>` cleanup after navigating away
